### ISSUE TITLE
请教/model/list怎么调用呢

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-api#10]
![image](https://github.com/MartialBE/one-api/assets/95951386/61169199-2093-4944-9561-91562d72c7a4)

请问这个是在哪个接口调用呢？

**Comment by woodchen-ink** [comment]
如果大佬有空的话，不知道能否加到下面的图片处呢，非常非常感谢
![image](https://github.com/MartialBE/one-api/assets/95951386/1787198b-09eb-4796-8a88-a7f0211eba78)

**Comment by MartialBE** [comment]
调用方法和 OpenAI的model list 接口是一样的
https://platform.openai.com/docs/api-reference/models/list

**Comment by woodchen-ink** [comment]
> 调用方法和 OpenAI的model list 接口是一样的 https://platform.openai.com/docs/api-reference/models/list

明白了，谢谢

**Comment by woodchen-ink** [comment]
![image](https://github.com/MartialBE/one-api/assets/95951386/c2af9bb3-1250-45c2-abd8-fc55b3677bc6)
返回值里没有owned_by
没办法做分类了
![image](https://github.com/MartialBE/one-api/assets/95951386/4e10a6fc-a384-4c9f-af45-80d46fbc0928)

**Comment by MartialBE** [comment]
我想想 看怎么解决好些

**Comment by woodchen-ink** [comment]
嗯嗯
