### ISSUE TITLE
在编辑渠道，插件参数输入内容后，无法编辑删除。 

### ISSUE THREAD

**Issue by Bossjava** [MartialBE/one-api#103]
在编辑渠道，插件参数输入内容后，无法通过再次编辑清空这个输入框的内容。 

当前版本：dev-27738aa

**Comment by MartialBE** [comment]
目前插件输入的内容，也就`zhipu`的知识库，我尝试了可以正常删除，也能正常保存。
你的复现步骤是什么

**Comment by Bossjava** [comment]
![20240313_120309](https://github.com/MartialBE/one-api/assets/53845535/5ed7a8ad-e159-4b48-a028-611fb4aa6875)

复现步骤

**Comment by MartialBE** [comment]
明白了， 我以为是 最下面的设置插件功能有问题。
你觉得，这里是直接填写好呢，还是也像下面开启联网一样，使用开关配置好呢？

**Comment by MartialBE** [comment]
已修复
