### ISSUE TITLE
panic detected: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by blackh1** [MartialBE/one-api#106]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
会报错
**复现步骤**
暂时未知如何复现，以下为报错日志
**预期结果**

**相关截图**
[SYS] 2024/03/13 - 11:00:14 | panic detected: runtime error: invalid memory address or nil pointer dereference 
[SYS] 2024/03/13 - 11:00:14 | stacktrace from panic: goroutine 344 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
one-api/router.SetRelayRouter.RelayPanicRecover.func3.1()
        /build/middleware/recover.go:17 +0x70
panic({0xfd9fe0?, 0x243e080?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
one-api/common.ErrorWrapper({0x0?, 0x0?}, {0x1138c04, 0x16}, 0x1f4)
        /build/common/gin.go:37 +0x3a
one-api/providers/minimax.(*MiniMaxProvider).getChatRequest(0xc00091a0e0, 0xc000188038)
        /build/providers/minimax/chat.go:65 +0x198
one-api/providers/minimax.(*MiniMaxProvider).CreateChatCompletionStream(0xc00091a0e0, 0xc000188038)
        /build/providers/minimax/chat.go:36 +0x45
one-api/controller/relay.(*relayChat).send(0xc000188000)
        /build/controller/relay/chat.go:56 +0x8a
one-api/controller/relay.RelayHandler({0x1d8a398, 0xc000188000})
        /build/controller/relay/main.go:97 +0xc3
one-api/controller/relay.Relay(0xc0006daa00)
        /build/controller/relay/main.go:30 +0xbb
github.com/gin-gonic/gin.(*Context).Next(0xc0006daa00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
one-api/router.SetRelayRouter.Distribute.func5(0xc0006daa00)
        /build/middleware/distributor.go:14 +0x59
github.com/gin-gonic/gin.(*Context).Next(0xc0006daa00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
one-api/router.SetRelayRouter.TokenAuth.func4(0xc0006daa00)
        /build/middleware/auth.go:123 +0x1af
github.com/gin-gonic/gin.(*Context).Next(0xc0006daa00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
one-api/router.SetRelayRouter.RelayPanicRecover.func3(0xc0006daa98?)
        /build/middleware/recover.go:27 +0x45
github.com/gin-gonic/gin.(*Context).Next(0xc0006daa00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
main.main.Sessions.func3(0xc0006daa00)
        /go/pkg/mod/github.com/gin-contrib/sessions@v0.0.5/sessions.go:54 +0x169
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1(0xc0006daa00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 +0xdd
github.com/gin-gonic/gin.(*Context).Next(0xc0006daa00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 +0x2b
main.main.RequestId.func2(0xc0006daa00)
        /build/middleware/request-id.go:19 +0x1a7
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1(0xc0006daa00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 +0x7a
github.com/gin-gonic/gin.(*Context).Next(...)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc00023cd00, 0xc0006daa00)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 +0x66e
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc00023cd00, {0x1d82370, 0xc00091a000}, 0xc0008ac000)
        /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 +0x1b2
net/http.serverHandler.ServeHTTP({0x1d7f278?}, {0x1d82370?, 0xc00091a000?}, 0x6?)
        /usr/local/go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc000b32000, {0x1d845b0, 0xc00017b8f0})
        /usr/local/go/src/net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
        /usr/local/go/src/net/http/server.go:3285 +0x4b4
如果没有的话，请删除此节。

**Comment by blackh1** [comment]
使用minimax渠道就会报错这个，是因为没有适配嘛？

**Comment by MartialBE** [comment]
你请求 minimax 的 内容是什么。
直接请求的api还是使用哪个工具（next chat/lobe chat）？

**Comment by MartialBE** [comment]
已修复。
你忘记填写 group_id 了。
minimax 的key 按照如下格式输入：APISecret|groupID

**Comment by blackh1** [comment]
![image](https://github.com/MartialBE/one-api/assets/74771265/aa60f7b1-8006-433e-b377-a73a5957db89)
日志里不会统计补全的token数

**Comment by MartialBE** [comment]
已修复， stream 下minimax未计算token的问题
