### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-api#108]
![image](https://github.com/MartialBE/one-api/assets/95951386/5ba9e2d7-3db9-4b5f-b505-3e34f77be836)

**Comment by woodchen-ink** [comment]
这个报错是在新建渠道时,初始化权重导致的

**Comment by woodchen-ink** [comment]
我想问下, 这个权重好像设置了数值后,就不能再关闭了, 那么旧的渠道的权重为0 , 会导致错误吗?

**Comment by MartialBE** [comment]
你是每次新建渠道的时候，都会报错吗？

> 我想问下, 这个权重好像设置了数值后,就不能再关闭了, 那么旧的渠道的权重为0 , 会导致错误吗?

不会，我设置了默认值是 1.旧的渠道权重0，在初始化时，会改为1。 你上面那个报错就是在改成1的时候报错了。

**Comment by MartialBE** [comment]
看起来好像是 DefaultChannelWeight 还没初始化时，就被引用了。
你现在还能重新启动吗

**Comment by woodchen-ink** [comment]
> 看起来好像是 DefaultChannelWeight 还没初始化时，就被引用了。 你现在还能重新启动吗

无法启动, 我去数据库把这个新建的渠道删掉后恢复正常

**Comment by MartialBE** [comment]
你是把数据库weight默认值设置为null了吗？

**Comment by woodchen-ink** [comment]
> 你是把数据库weight默认值设置为null了吗？

我没有设置过, 自动变成null了

**Comment by MartialBE** [comment]
删除的时候变空值了？ 你的意思是 在后台删除后，数据库还存在 这个记录，但是值全部变成null了吗？
你创建完毕后，数据库中 weight 的值是什么？
数据库 channel表结构中 weight 有 `DEFAULT '1'`吗？


> > 看起来好像是 DefaultChannelWeight 还没初始化时，就被引用了。 你现在还能重新启动吗
> 
> 无法启动, 我去数据库把这个新建的渠道删掉后恢复正常

删除的时候记得还要去 `abilities`表删除对应的数据。

**Comment by woodchen-ink** [comment]
> abilities

我详细描述下:  
1. 更新后, 有一些渠道权重还是为0, 有几个没设置过权重的数值变为了`1`,包括这个新建的渠道, 新建后一切正常. 然后测试, 提示无权限, 我去grop上看了看, 回来再测, 失败. 切换模型为接近32k的那个, 测试,失败, 再去grop上看了看, 回来切换测试模型无反应, 我以为页面卡了, 刷新页面, 渠道页面处 该渠道的值都消失了,但是这一行还在;
2. 我去看了docker日志, 报我截图错误, 我切换为上个版本, 无法启动, 提示数据库值有问题;
3. 我去数据库找到这个渠道, 除了权重为`NULL`外,其他的值全部为空白, 我删除后, 重启docker,成功启动

这是目前`abilties`表里的样子:
![image](https://github.com/MartialBE/one-api/assets/95951386/b4911342-a9bc-4a49-9d84-ad2ffc3c4cc1)

**Comment by woodchen-ink** [comment]
![image](https://github.com/MartialBE/one-api/assets/95951386/6c5a3333-429f-428f-97bc-24b26535cf0a)
默认为1

**Comment by woodchen-ink** [comment]
我的数据库版本是 mariadb-10.4.19 , 因为我是4G运存的小机子,装MySQL8装不了

**Comment by MartialBE** [comment]
我知道为什么， 你现在千万不要点击 更新权重和优先级。。 SQL有问题，点击了就会删除所有其他字段

**Comment by MartialBE** [comment]
已修复

**Comment by woodchen-ink** [comment]
> 我知道为什么， 你现在千万不要点击 更新权重和优先级。。 SQL有问题，点击了就会删除所有其他字段

啊,对的,我点击了这个, 我好像漏说了

**Comment by woodchen-ink** [comment]
> 已修复

我拉取试试

**Comment by woodchen-ink** [comment]
还好我没点其他渠道的更新权重/优先级, 不然我得哭哈哈

**Comment by MartialBE** [comment]
修复一个bug引发另一个bug....😂

**Comment by woodchen-ink** [comment]
> 修复一个bug引发另一个bug....😂

哈哈, 我现在拉取你的代码都不做测试了, 直接更新容器, 完全不怂

**Comment by woodchen-ink** [comment]
目前一切OK, 测试也可以用了,非常棒, tks
