### ISSUE TITLE
倍率设置优化

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-api#109]
我想问一下，目前当模型价格变动时，你是怎么调整的😂

我发现好难调整呐，只好拉取你的`dev`镜像, 构建一个容器从里面复制🤦‍♂️, 感觉方法好蠢的样子

## 有没有一种办法, 在下图这个位置加一下按钮: 
![image](https://github.com/MartialBE/one-api/assets/95951386/655d1c53-79c3-4c26-ac9e-ec52a240f495)

这样会不会方便一点

## 我想在文档站可以获取这个值, 然后作为上面图里这样的表格展示, 有这个接口吗? 或者有其他实现方法不?

我的全是官方倍率,但是想把成本为0的渠道改为免费, 所以就有这个考虑

**Comment by MartialBE** [comment]
我准备改价格机制。
准备独立一个菜单设置价格。
一个价格下面绑定多个模型。
然后可以远程拉取我设置的官方价格配置。

**Comment by woodchen-ink** [comment]
> 我准备改价格机制。 准备独立一个菜单设置价格。 一个价格下面绑定多个模型。 然后可以远程拉取我设置的官方价格配置。

这么好🤣，厉害了👍，听起来比我提的好太多了

**Comment by woodchen-ink** [comment]
突然想到, 这个官方价格配置, 可以放到这个github里面, 弄个json或者csv格式, 如果价格变动可以直接PR

**Comment by MartialBE** [comment]
是的。但是如果已经存在的模型倍率 就不会同步。
你可以试试看， 新的提交新增了 `claude-3-haiku-20240307`模型， 更新后 你什么都不做，看看后台有没有这个模型的倍率了

**Comment by woodchen-ink** [comment]
> 是的。但是如果已经存在的模型倍率 就不会同步。 你可以试试看， 新的提交新增了 `claude-3-haiku-20240307`模型， 更新后 你什么都不做，看看后台有没有这个模型的倍率了

![image](https://github.com/MartialBE/one-api/assets/95951386/b08d8634-968a-424e-bbf2-e67e7c199ab0)
有的,这个功能好像前几个版本就有了

**Comment by MartialBE** [comment]
已支持， 有破坏性更新，请注意查看 #128  的说明。
