### ISSUE TITLE
dashboard的统计的时间好像不太对

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-api#11]
![image](https://github.com/MartialBE/one-api/assets/95951386/4e536780-e4d6-47de-af59-ccc6d6ab7cfa)

显示的是前一天的，变量里已经指定了时区
![image](https://github.com/MartialBE/one-api/assets/95951386/6e58e9e9-863e-4ed6-a5fb-ecf1dc7c6d7e)

**Comment by MartialBE** [comment]
已修复，可以拉取最新代码编译一下  或者拉取dev的 docker镜像
