### ISSUE TITLE
是否能提供arm64位的docker镜像？

### ISSUE THREAD

**Issue by YanxingLiu** [MartialBE/one-api#111]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

尝试使用fork了的版本采用github actions编译，但是每次actions push都会遇到403 forbidden

**Comment by MartialBE** [comment]
dockerhub 的token 有设置吗？
我等下加一个arm64的镜像

**Comment by MartialBE** [comment]
已添加arm64镜像，目前只有 martialbe/one-api:dev有， 正式版本号还没

**Comment by YanxingLiu** [comment]
> 已添加arm64镜像，目前只有 martialbe/one-api:dev有， 正式版本号还没

好的，感谢

**Comment by YanxingLiu** [comment]
> dockerhub 的token 有设置吗？ 我等下加一个arm64的镜像

我注释了dockerhub 的push，只上传到github到packages，但是提示没权限上传上去，其他repo也有很多人报告这个错误。

**Comment by MartialBE** [comment]
去GitHub 设置中创建一个密钥 然后去在你的GitHub项目中 设置一个密钥变量，替换掉 action中 secrets.GITHUB_TOKEN  的变量名。
或者 去你的packages设置你对应的GitHub项目读写权限

**Comment by YanxingLiu** [comment]
> 去GitHub 设置中创建一个密钥 然后去在你的GitHub项目中 设置一个密钥变量，替换掉 action中 secrets.GITHUB_TOKEN 的变量名。 或者 去你的packages设置你对应的GitHub项目读写权限

好的，我试试。
