### ISSUE TITLE
删除中间商

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-api#112]
我想删除那些杂七杂八的中间商,精简下代码

我搜了一下发现相关代码有点多, 可以问下具体大概需要删哪些吗?
![image](https://github.com/MartialBE/one-api/assets/95951386/1c188bf1-9d19-4bad-9fa5-df1efb0c1c06)
是这5个文件?

**Comment by MartialBE** [comment]
删除 providers 文件夹对应供应商的文件夹 以及 providers.go中对应的map。
还有前端的web/src/constants/ChannelConstants.js对应的供应商。

推荐只删除前端的供应商配置文件。不影响使用。

**Comment by woodchen-ink** [comment]
> 删除 providers 文件夹对应供应商的文件夹 以及 providers.go中对应的map。 还有前端的web/src/constants/ChannelConstants.js对应的供应商。
> 
> 推荐只删除前端的供应商配置文件。不影响使用。

谢谢,前端我之前已经删掉了,我主要是想把后端的也删掉. 我试试

如果可以的话, 这些能全部删完就好了, 把过去的记录也删掉,这些都是自定义渠道就能代替的,还多了那么多代码
