### ISSUE TITLE
选择两个分组，并且选择填入所有模型，就会报SQL错误

### ISSUE THREAD

**Issue by Bossjava** [MartialBE/one-api#113]
![image](https://github.com/MartialBE/one-api/assets/53845535/cc79da65-67ee-457c-b9be-c024653edc18)

选择两个分组，并且选择填入所有模型，就会报SQL错误

当前版本：dev-27738aa

**Comment by MartialBE** [comment]
你把终端的错误信息复制给我。

**Comment by Bossjava** [comment]
> {
>     "name": "111",
>     "type": 1,
>     "key": "1",
>     "base_url": "1111",
>     "other": "",
>     "proxy": "",
>     "test_model": "",
>     "model_mapping": "",
>     "models": "360GPT_S2_V9,embedding_s1_v1,embedding-bert-512-v1,semantic_similarity_s1_v1,qwen-max,qwen-max-longcontext,qwen-plus,qwen-turbo,qwen-vl-max,qwen-vl-plus,text-embedding-v1,claude-2.0,claude-2.1,claude-3-opus-20240229,claude-instant-1.2,Baichuan-Text-Embedding,Baichuan2-53B,Baichuan2-Turbo,Baichuan2-Turbo-192k,BLOOMZ-7B,Embedding-V1,ERNIE-3.5-8K,ERNIE-4.0,ERNIE-Bot,ERNIE-Bot-4,ERNIE-Bot-8k,ERNIE-Bot-turbo,ERNIE-Speed,deepseek-chat,deepseek-coder,gemini-pro,gemini-pro-vision,PaLM-2,abab5.5-chat,abab5.5s-chat,abab6-chat,embo-01,mistral-embed,mistral-large-latest,mistral-medium-latest,mistral-small-latest,open-mistral-7b,open-mixtral-8x7b,moonshot-v1-128k,moonshot-v1-32k,moonshot-v1-8k,ada,babbage,babbage-002,code-davinci-edit-001,curie,dall-e-2,dall-e-3,davinci,davinci-002,gpt-3.5-turbo,gpt-3.5-turbo-0125,gpt-3.5-turbo-0301,gpt-3.5-turbo-0613,gpt-3.5-turbo-1106,gpt-3.5-turbo-16k,gpt-3.5-turbo-16k-0613,gpt-3.5-turbo-instruct,gpt-4,gpt-4-0125-preview,gpt-4-0314,gpt-4-0613,gpt-4-1106-preview,gpt-4-32k,gpt-4-32k-0314,gpt-4-32k-0613,gpt-4-preview,gpt-4-turbo-preview,gpt-4-vision-preview,text-ada-001,text-babbage-001,text-curie-001,text-davinci-002,text-davinci-003,text-davinci-edit-001,text-embedding-3-large,text-embedding-3-small,text-embedding-ada-002,text-moderation-latest,text-moderation-stable,text-search-ada-doc-001,tts-1,tts-1-1106,tts-1-hd,tts-1-hd-1106,whisper-1,hunyuan,SparkDesk,SparkDesk-v1.1,SparkDesk-v2.1,SparkDesk-v3.1,SparkDesk-v3.5,cogview-3,embedding-2,glm-3-turbo,glm-4,glm-4v",
>     "groups": [
>         "default",
>         "folotoy"
>     ],
>     "plugin": {},
>     "is_edit": false,
>     "group": "default,folotoy"
> }
> 





# 错误信息
`{"message":"too many SQL variables","success":false}`

**Comment by MartialBE** [comment]
拉取最新的dev再试试

**Comment by 1395173231** [comment]
这个问题可以尝试将func (channel *Channel) AddAbilities()方法中的
DB.Create(&abilities).Error
替换为
DB.CreateInBatches(&abilities,20).Error

**Comment by MartialBE** [comment]
和 `github.com/mattn/go-sqlite3` 的版本有关系。
`v2.0.1+incompatible`版本确实会出现这个问题(这个版本也撤销了)，因为它使用的是SQLite ` 3.30.1`，默认的`SQLITE_MAX_VARIABLE_NUMBER` 为 999。而SQLite`3.32.0`开始改该值为`32766`。
所以拉取最新版也可以解决这个问题
