### ISSUE TITLE
提示的token计算有问题

### ISSUE THREAD

**Issue by 1395173231** [MartialBE/one-api#116]
如图,与上游存在较大的计算差异
![image](https://github.com/MartialBE/one-api/assets/35016247/bb4bfc4e-f964-401a-a547-75f57db9a7f6)
![image](https://github.com/MartialBE/one-api/assets/35016247/e1e327a7-ff0e-49f9-9d36-e44ea4323d42)
查看代码发现重复计算了消息内容的token
https://github.com/MartialBE/one-api/blob/d4003f24bf307c63ee7e6893cd34dc56d194d036/common/token.go#L111

**Comment by MartialBE** [comment]
感谢，已修复
