### ISSUE TITLE
什么时候支持绘画啊

### ISSUE THREAD

**Issue by 56025192** [MartialBE/one-api#118]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

**应用场景**

**Comment by MartialBE** [comment]
你是指 mj的绘画吗？ 我这个没有帐号，而且它不支持API调用，暂时没计划支持。

**Comment by 56025192** [comment]
> 你是指 mj的绘画吗？ 我这个没有帐号，而且它不支持API调用，暂时没计划支持。

还有sd

**Comment by MartialBE** [comment]
bedrock 中的`Stability AI`可以配置。
不过我看了一下`Stability AI`的参数， `OpenAI`的`ImageGenerate`接口参数很少， 转换成`Stability AI`会少很多可以自定义的参数。
