### ISSUE TITLE
dial tcp: lookup xxx: i/o timeout

### ISSUE THREAD

**Issue by idelin** [MartialBE/one-api#119]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
请求时都会报超时，检查了环境的dns，都是正常的，ping都可以通，这个问题出现在哪？

relay error (channel #2(月之暗面)): Post "https://api.moonshot.cn/v1/chat/completions": dial tcp: lookup api.moonshot.cn: i/o timeout (request id: 20240321101044652332146t0LUYqfX)

relay error (channel #1(讯飞星火)): dial tcp: lookup spark-api.xf-yun.com: i/o timeout (request id: 2024032110191353165130263ACLn6X)

**复现步骤**
请求即会报错

**预期结果**
可以成功请求

**相关截图**
relay error (channel #1(讯飞星火)): dial tcp: lookup spark-api.xf-yun.com: i/o timeout (request id: 2024032110191353165130263ACLn6X)

<img width="456" alt="image" src="https://github.com/MartialBE/one-api/assets/23070481/51202fa8-c92d-48d1-a36c-7fc45f63778c">

**Comment by MartialBE** [comment]
你的DNS解析是否很慢？
你可以尝试把  环境变量`CONNECT_TIMEOUT` 设置长一些再试试。
`CONNECT_TIMEOUT`默认值是5秒， 你可以设置 10秒看看

**Comment by idelin** [comment]
设置了CONNECT_TIMEOUT，可是还是一样的问题 @MartialBE

**Comment by idelin** [comment]
咦，我重新再试了下，发现moonshot的可以了，讯飞的还不行，233，这个CONNECT_TIMEOUT单位是什么，毫秒吗

**Comment by MartialBE** [comment]
讯飞使用的 wss 没有引用我的超时设置，我配置一下。

**Comment by MartialBE** [comment]
好了， 等GitHub Actions 编译完成后，重新拉取一下 dev 版本的镜像试试
