### ISSUE TITLE
gemini返回有问题

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-api#120]
![image](https://github.com/MartialBE/one-api/assets/95951386/1d069870-b8ec-44a7-b6f7-6a033455a9bb)
![image](https://github.com/MartialBE/one-api/assets/95951386/7cd73533-1594-414b-9782-17ea36ee3ee2)
日志有返回, 但是对话平台上用没有返回信息
![image](https://github.com/MartialBE/one-api/assets/95951386/1bdb109c-c661-4fa7-85e1-9ce9aaea5f01)
![image](https://github.com/MartialBE/one-api/assets/95951386/1cd3e213-a3d4-4947-9d2e-6ab04f441ec3)
之前我还以为是我节点问题, 现在换成新加坡服务器了还是不行

**Comment by woodchen-ink** [comment]
之前是香港套代理, 我一直以为是代理的问题.

**Comment by MartialBE** [comment]
好像next chat是有问题。
lobe chat可以正常使用。

**Comment by woodchen-ink** [comment]
> 好像next chat是有问题。 lobe chat可以正常使用。



> 好像next chat是有问题。 lobe chat可以正常使用。

我的另一个商业镜像站也用不了, 用别人one-api的中转就可以, 很奇怪

**Comment by woodchen-ink** [comment]
> ![image](https://private-user-images.githubusercontent.com/42402987/316014774-d629b15f-aa45-422d-bcde-396219944573.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMTI1MzQsIm5iZiI6MTcxMTExMjIzNCwicGF0aCI6Ii80MjQwMjk4Ny8zMTYwMTQ3NzQtZDYyOWIxNWYtYWE0NS00MjJkLWJjZGUtMzk2MjE5OTQ0NTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDEyNTcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMzI5ODRkYWE5MzRjYzNiNTE1ZGZiODQ5MDAxOWI2OWVkM2ViMjg3MjhmYjk0M2ViMWI1ZTk0ZTIyZWEyM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rT6Y6lao37yKdG3QJ3MZZ6OKBxPyunP5crqpwFoJHhs)
> 
> Next chat 请求gemini时使用的是gemini的api格式 不是openai的 你试试lobe chat

lobe chat我没试, 没部署, 用了单一网页调用成功了, 我的镜像站错误, 
![image](https://github.com/MartialBE/one-api/assets/95951386/a0cfd458-ae93-4629-b239-258668c60ba0)
其他模型都可以, 只有gemini pro不行

**Comment by woodchen-ink** [comment]
![image](https://github.com/MartialBE/one-api/assets/95951386/177cf50f-34a9-4d5b-b674-065486e058f4)
不知道哪里有问题

**Comment by MartialBE** [comment]
镜像网站是用同一个one api吗？
这个400我感觉像是 代理地址的问题。

**Comment by woodchen-ink** [comment]
是同一个one api

应该不是地址问题, 因为我别的模型是OK的, 同一个key同一个地址

咱们这版gemini的代码和原版有区别吗?


[image]

> ***@***.***>
> 时间： 2024年3月22日 (周五) 21:22
> 主题： Re: [MartialBE/one-api] gemini返回有问题 (Issue #120)
> ***@***.***>
> 抄送："wood ***@***.***>, ***@***.***>
> 镜像网站是用同一个one api吗？
> 
这个400我感觉像是 代理地址的问题。

**Comment by woodchen-ink** [comment]
![XfeqbyPNDoZzdoxyELMcmaE6nCf](https://github.com/MartialBE/one-api/assets/95951386/36668d9a-cb82-4ae0-8214-0bfc6827db5c)

**Comment by MartialBE** [comment]
之前是一样的 很久没同步上游代码了。
我试了使用lobe chat。opencat。 直接api请求都能成功。

**Comment by woodchen-ink** [comment]
> 之前是一样的 很久没同步上游代码了。 我试了使用lobe chat。opencat。 直接api请求都能成功。

😭有空帮忙看看呗

**Comment by MartialBE** [comment]
如果原版没问题的话。你可以对比对比代码看看。
这几天出去玩没时间😂

**Comment by woodchen-ink** [comment]
> 如果原版没问题的话。你可以对比对比代码看看。 这几天出去玩没时间😂

哈哈,好的, 我自己看看, 玩的开心

**Comment by hcppxgit** [comment]
是nextchat前端的问题，简单理解就是他那个前端只要在模型名检测到gemini之类的就会自动在前端里面寻找相对应的谷歌配置，如果未在前端配置谷歌接口等信息，就会直接出错，不会尝试请求你这个openai的通道，解决办法是在oneapi后台做一个模型映射，给gemini换个别的模型名去请求，然后在前端那边再添加这个映射过后的新模型名
