### ISSUE TITLE
希望能增加模型测试通道响应时间的功能，以便于判断哪些渠道的模型响应更加迅速

### ISSUE THREAD

**Issue by geekbb** [MartialBE/one-api#121]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
[+] 我已确认目前没有类似 issue
[+] 我已确认我已升级到最新版本
[+] 我已完整查看过项目 README，已确定现有版本无法满足需求
[+] 我理解并愿意跟进此 issue，协助测试和提供反馈
[+] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
希望增加以模型测试渠道响应时间
**应用场景**
<img width="258" alt="image" src="https://github.com/MartialBE/one-api/assets/46196358/7effe62b-fd61-4b06-9a41-391f59b857e2">

**Comment by MartialBE** [comment]
已添加
