### ISSUE TITLE
大佬会考虑接入midjourney-proxy-plus和易支付吗

### ISSUE THREAD

**Issue by homestoo** [MartialBE/one-api#122]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
midjourney-proxy-plus可代理mj使用
易支付直接中转里面支付，用兑换码还是不方便

**应用场景**

**Comment by woodchen-ink** [comment]
我倒希望能接stripe

**Comment by MartialBE** [comment]
mj没有帐号，不好对接...
支付的话，后面再支持

**Comment by MartialBE** [comment]
#138
mj已支持， 该模块改自new api的代码。使用方式和它一致。

**Comment by mmwong1984** [comment]
易支付也可以改new api 的代码啊

**Comment by MartialBE** [comment]
#250 
已支持
