### ISSUE TITLE
模型名称可以支持通配符吗

### ISSUE THREAD

**Issue by quebra** [MartialBE/one-api#123]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
希望添加模型名称可以支持通配符 比如 gpt-4-gizmo-*
**应用场景**
现在想添加gpts商店自定义的模型需要一个一个的填进去, 比如 gpt-4-gizmo-g-U1EuXEZ6Y
希望添加自定义模型的时候可以以通配符形式添加

**Comment by MartialBE** [comment]
这周处理

**Comment by MartialBE** [comment]
已支持， 有破坏性更新，请注意查看 #128  的说明。
