### ISSUE TITLE
编译失败，  go build main.go:21:12: pattern web/build: no matching files found

### ISSUE THREAD

**Issue by zsinba** [MartialBE/one-api#124]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
下载后，在mac下面编译失败。
**复现步骤**
go build
**预期结果**
编译成功
**相关截图**
 main.go:21:12: pattern web/build: no matching files found
<img width="315" alt="image" src="https://github.com/MartialBE/one-api/assets/890157/56a926c9-f0cc-4ebb-ba6a-b48ab2221a16">

**Comment by MartialBE** [comment]
你没有编译前端页面。
看下面的部署方式：
https://github.com/MartialBE/one-api/wiki/Deployment#%E6%89%8B%E5%8A%A8%E9%83%A8%E7%BD%B2

**Comment by MartialBE** [comment]
最新代码 加了个 makefile。
你安装好`npm` 和 go后，可以直接通过 `make` 命令编译。 如果需要重新编译 请先执行`make clean` 再执行`make`。
