### ISSUE TITLE
讯飞星火无法正常使用

### ISSUE THREAD

**Issue by cnliucheng** [MartialBE/one-api#129]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [ x 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
接入讯飞星火SparkDesk-v3.5模型，使用fastgpt无论输入任何内容，均返回内容违规的10013错误提示，即使输入“红烧肉怎么做”也是如此。换成其它例如百度或者阿里，均可以正常使用

**复现步骤**

**预期结果**

**相关截图**
![QQ截图20240326123155](https://github.com/MartialBE/one-api/assets/32115849/f5285d83-7e5a-4aed-a597-5bc41102361b)

**Comment by MartialBE** [comment]
这是讯飞返回的错误，和我这边没有关系，请检查你的讯飞帐号是否有问题

**Comment by cnliucheng** [comment]
的确和one-api没关系，撇开fastgpt，直接用lobe-chat接入one-api使用，则没有出现该问题。

**Comment by MartialBE** [comment]
你看看是不是你fastgpt里面设置什么提示词。或者知识库有什么问题。你在fastgpt编辑界面测试一下就知道了

**Comment by cnliucheng** [comment]
已解决，在建知识库的时候，选择索引模型的时候用“text-embedding-ada-002”就可以了。

**Comment by cnliucheng** [comment]
最终发现在fastgpt新建应用的时候，问题优化模型不能选择讯飞，选其它的都可以，选择讯飞就会报错，原因不明。
