### ISSUE TITLE
暗色模式

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-api#130]
突然想加个暗色模式, 能指导下在哪加不😄

**Comment by MartialBE** [comment]
emmm.我也是前端小白...也得查资料...
接口一分钟前端一小时...

**Comment by woodchen-ink** [comment]
> emmm.我也是前端小白...也得查资料... 接口一分钟前端一小时...

哈哈哈哈, 没想到是后端大佬

**Comment by MartialBE** [comment]
昨天简单改了一下深色模式...
配色要改好多地方... 这个前端开源版本把深色模式去掉了。 然后我自己加的组件之前没考虑深色。这是个细活...

**Comment by woodchen-ink** [comment]
> 昨天简单改了一下深色模式... 配色要改好多地方... 这个前端开源版本把深色模式去掉了。 然后我自己加的组件之前没考虑深色。这是个细活...

😏
能不能弄成css变量去控制, 彩色的组件颜色好像都不用换, 主要就是背景色和字体色

**Comment by woodchen-ink** [comment]
![image](https://github.com/MartialBE/one-api/assets/95951386/c958e674-37c3-4703-9ba1-5ee0ef97eac1)
这个用的dark reader浏览器插件

**Comment by MartialBE** [comment]
是变量控制。
说是细活就是要配色搭配。以及自己写的组件改成使用配色变量。
前端好烦😫。我本地好几个分支都是前端更改的分支放那里不想动了...

**Comment by woodchen-ink** [comment]
> 是变量控制。 说是细活就是要配色搭配。以及自己写的组件改成使用配色变量。 前端好烦😫。我本地好几个分支都是前端更改的分支放那里不想动了...

👻👻👻

**Comment by woodchen-ink** [comment]
![image](https://github.com/MartialBE/one-api/assets/95951386/1098ae51-50e6-4125-a57c-e2414e7352a0)
我好像看到了什么

**Comment by MartialBE** [comment]
就是这个。有颜色 但是要搭配来着

**Comment by MartialBE** [comment]
#134
已知问题： 首页 切换按钮未水平对齐/ 移动端下导航栏拥挤。

**Comment by woodchen-ink** [comment]
强👍

**Comment by woodchen-ink** [comment]
大佬,咋指定暗色

**Comment by MartialBE** [comment]
指定？ 默认暗色吗？

**Comment by woodchen-ink** [comment]
Message ID: ***@***.***>
是哒

**Comment by MartialBE** [comment]
改这里，不过不建议改，`dark`下有好多细节没弄， 感觉挺丑的，但是改烦了，暂时不想改它了：
https://github.com/MartialBE/one-api/blob/65820c0ff8dc8b4bcb395466e014b3e7fa5fcf2d/web/src/store/customizationReducer.js#L13

**Comment by woodchen-ink** [comment]
好的, 等我啥时候有空自己慢慢改着玩

**Comment by woodchen-ink** [comment]
![image](https://github.com/MartialBE/one-api/assets/95951386/3e79422d-78f7-403a-8ff4-47bd35847c0e)
首页右侧我改成这样了, 新版只有一个人员头像, 要进入面板稍微有点麻烦

**Comment by woodchen-ink** [comment]
``` 
{account.user ? (
              <>
              <Button component={Link} variant="contained" to="/panel" color="primary">
              控制台
            </Button>
              <ProfileSection />
              </>
            ) : (
              <Button component={Link} variant="contained" to="/login" color="primary">
                登录
              </Button>
            )}
```

**Comment by MartialBE** [comment]
本来是要加上去的 后面改了手机端后给忘了

**Comment by woodchen-ink** [comment]
![image](https://github.com/MartialBE/one-api/assets/95951386/11125d5a-3563-4830-bcee-15d4daf2e8ad)
![image](https://github.com/MartialBE/one-api/assets/95951386/7b0ae31a-dbe3-4e2c-b127-b40affc4bbcb)

完美, 感谢大佬
