### ISSUE TITLE
项目中的 docker-compose.yml 文件中，仍然使用的是 justsong/one-api:latest 

### ISSUE THREAD

**Issue by geekbb** [MartialBE/one-api#131]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
[+] 我已确认目前没有类似 issue
[+] 我已确认我已升级到最新版本
[+] 我已完整查看过项目 README，尤其是常见问题部分
[+] 我理解并愿意跟进此 issue，协助测试和提供反馈 
[+] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
一、![CleanShot 2024-03-29 at 12 59 57@2x](https://github.com/MartialBE/one-api/assets/46196358/37a24c64-e0b4-4900-a70b-6ed1cbff5754)

二、从 v0.6.4 升级到 v0.7.0 是否一定需要使用 config.yaml 文件。
   是否是将 config.yaml 放置运行目录，直接更新即可？

**复现步骤**

**预期结果**
我是新手，进行拉取时多次不小心拉成了原 one-api 版本😅
**相关截图**
如果没有的话，请删除此节。

**Comment by MartialBE** [comment]
这个忘记改了...
不用 环境变量同样生效， 只是多一种配置的方式而已。

**Comment by MartialBE** [comment]
已修复
