### ISSUE TITLE
提个小功能请求

### ISSUE THREAD

**Issue by cheungchazz** [MartialBE/one-api#133]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
佬，发现站有个问题，在其他设置替换logo图片后以及设置自定义页脚，网页每次刷新都会先显示原有logo和页脚然后再显示替换后的

功能需求：能否添加多一个替换favicond的功能

**应用场景**

**Comment by woodchen-ink** [comment]
这个得自己fork改

原项目也是一样的

**Comment by cheungchazz** [comment]
好

**Comment by MartialBE** [comment]
如果自己建站的话 最好还是自己更改一下前端页面。 这样自定义更多而且也可以自己编写seo。 
后台控制更改只是为了方便简单部署的人。
