### ISSUE TITLE
在Wiki部署教程中是否可以将完善 MySQL 安装命令

### ISSUE THREAD

**Issue by igeekbb** [MartialBE/one-api#143]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
[+] 我已确认目前没有类似 issue
[+] 我已确认我已升级到最新版本
[+] 我已完整查看过项目 README，已确定现有版本无法满足需求
[+] 我理解并愿意跟进此 issue，协助测试和提供反馈
[+] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
![CleanShot 2024-04-09 at 13 45 28@2x](https://github.com/MartialBE/one-api/assets/154116268/aa3f85b2-c5c2-462f-8acc-22628d0e0eb1)

**应用场景**
很多小白没有安装过MySQL(比如我)，是否可以将MySQL dokcer部署命令一并写入教程，无脑一键安装？

**Comment by MartialBE** [comment]
可以看这里： https://github.com/MartialBE/one-api/wiki/Deployment#%E4%BD%BF%E7%94%A8-docker-compose-%E8%BF%9B%E8%A1%8C%E9%83%A8%E7%BD%B2

`docker-compose.yml` 里面包含了 mysql/redis， 你可以把这个文件下载下来， 修改里面的参数 比如数据库用户密码这些，默认也可以。

然后在和`docker-compose.yml`相同的目录下，再创建`data/mysql`目录:
```shell
mkdir -p data/mysql
```

最后 执行：
```shell
docker-compose up -d
```


如果你在使用`portainer`，可以现在你的服务器创建好数据保存的目录。
然后去新建一个`stacks`， 把`docker-compose.yml`的内容复制进去，修改目录参数，就好了。

**Comment by MartialBE** [comment]
我更新了一下 wiki中关于 `docker-compose`的操作。
