### ISSUE TITLE
请问下：同样的倍率，可是消费的额度，就是比上游更少，这是什么问题呢？

### ISSUE THREAD

**Issue by 2644635282** [MartialBE/one-api#147]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
上游是Newapi，同样的倍率请求下，自己搭建的这个的消费会比newapi下面消费低，不太好设置倍率。

**相关截图**
![微信截图_20240412135135](https://github.com/MartialBE/one-api/assets/62086344/dc15c3e7-8c13-488f-9552-581ee72af1da)

**Comment by MartialBE** [comment]
这并不是bug，自己简单算一下就知道了。
你设置了 3.5 模型 输入与输出都是 0.75的倍率， 那么输入输出都是 $0.0015/k.
(你可以直接在模型价格中查看 人民币和美元的价格， 很符合直觉，和OpenAI这些厂商编写的定价是一致的)

计算如下：
(20+46)/1000*0.0015=0.000099 四舍五入0.0001
并没有问题。

反向 new-api才不好管理倍率，你只能设置 输入倍率， 输出倍率是他写死的。

**Comment by MartialBE** [comment]
你要同步你购买的openai商家的价格。你只需要去查看他们的输入输出定价。
自己去模型价格 按照上面的说明 转化成倍率输入进去即可。
