### ISSUE TITLE
自定义输入模型无法正常工作

### ISSUE THREAD

**Issue by so2liu** [MartialBE/one-api#148]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

OpenAI 更新了模型名称，多了个gpt-4-turbo。我看到最新的 commit 已经新增了这个模型名称，但是还在 dev 的镜像上，没有在 release 镜像上。我理解且感激。

现在我的疑惑是为什么无法使用自定义模型的功能在老的模型版本上实现这个模型 ID？添加后请求时会报错“无可用渠道”

**相关截图**
<img width="443" alt="image" src="https://github.com/MartialBE/one-api/assets/9153390/1878117f-ce7b-4ab3-b624-733a1b6c59e7">

<img width="706" alt="image" src="https://github.com/MartialBE/one-api/assets/9153390/db0fa7b6-2ad2-46c9-8926-2193b6ac3c28">

如果没有的话，请删除此节。

**Comment by MartialBE** [comment]
你回车或者点击选中了吗？ 不然是没有添加的。

更方便的是 后台-模型价格-更新价格-获取数据-仅添加新增 就更新新增模型了。
