### ISSUE TITLE
编辑用户时，修改什么参数都显示   错误：无效的参数

### ISSUE THREAD

**Issue by PeanutSplash** [MartialBE/one-api#150]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
编辑用户时，修改什么参数都显示    **错误：无效的参数**
**复现步骤**
![image](https://github.com/MartialBE/one-api/assets/98582625/009ff80a-7642-4a21-a427-d99ceeb7dda0)
修改用户余额
**预期结果**

**相关截图**
![image](https://github.com/MartialBE/one-api/assets/98582625/de08c36e-0913-4296-b3e6-955b0768d3e6)
![image](https://github.com/MartialBE/one-api/assets/98582625/1ed1486b-a4f6-4ebe-8c91-299d7c07205e)

**Comment by Hwenyi** [comment]
相同的问题

**Comment by MartialBE** [comment]
已修复
