### ISSUE TITLE
仪表盘统计功能失效

### ISSUE THREAD

**Issue by ifsherlock** [MartialBE/one-api#151]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述** 仪表盘统计功能失效，就第一天的统计数据800多次在那里，现在过去好几天了，再也没增长过了。日志可以看出来有正常请求使用的。

**复现步骤**

**预期结果**

**相关截图**
![QQ截图20240415032853](https://github.com/MartialBE/one-api/assets/85504065/7fec440c-0252-475b-9586-68a66ec1e0fa)
![QQ截图20240415032933](https://github.com/MartialBE/one-api/assets/85504065/11ea5308-7eac-4cf8-91e2-13d3a66ccadc)

**Comment by MartialBE** [comment]
1. 有无报错？
2. 用的什么数据库？ 有没有和其他的 one-api 混用数据库？
3. 快捷键 Command + Option + J (Mac) 或者 Control + Shift + J (Windows/Linux) 或者 鼠标右键 检查，打开控制台，然后刷新页面， 在 网络 中 找到`api/user/dashboard`的请求，点击， 里面的内容是什么。
