### ISSUE TITLE
docker-compose.yml 和 config.yaml 都设置的情况下，谁覆盖谁？

### ISSUE THREAD

**Issue by vongoethe** [MartialBE/one-api#153]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x] 我已确认目前没有类似 issue
+ [x ] 我已确认我已升级到最新版本
+ [x ] 我已完整查看过项目 README，尤其是常见问题部分
+ [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
请教一下，docker-compose.yml 和 config.yaml 都设置了参数的情况下，两边参数不一致的话以谁为准？
谢谢

**复现步骤**

**预期结果**

**Comment by MartialBE** [comment]
配置优先级： 环境变量 > 配置文件

docker compose 配置的是环境变量。

**Comment by vongoethe** [comment]
谢谢
