### ISSUE TITLE
模型价格 更新、覆盖均报错  

### ISSUE THREAD

**Issue by GettionHub** [MartialBE/one-api#154]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
模型价格覆盖报错"Error 1406 (22001): Data too long for column 'model' at row 27" 
仅添加更新 报错误: Error 1406 (22001): Data too long for column 'model' at row 1
**复现步骤**
切换回v0.7.4或者清空数据库以及重新装v0.7.5依旧报上述两个错误代码
数据库是群晖自带套件MariaDB 10版本号：10.11.2-1303

**Comment by MartialBE** [comment]
因为昨天新增了 [Cloudflare AI](https://ai.cloudflare.com/)的模型 ，模型名称比较长，旧版本的价格表的字段长度不够导致的。
已经发了 0.7.6版 等action 编译完成后 升级即可

**Comment by woodchen-ink** [comment]
> 因为昨天新增了 [Cloudflare AI](https://ai.cloudflare.com/)的模型 ，模型名称比较长，旧版本的价格表的字段长度不够导致的。 已经发了 0.7.6版 等action 编译完成后 升级即可

大佬, cf ai能给个创建页面的截图吗, 我没找着能在哪创建多个ai模型的worker

**Comment by woodchen-ink** [comment]
> 不用创建。
> 
> 1. 去[控制台](https://dash.cloudflare.com/) 随便点开一个域名， 然后在右下角 拿到你的 account ID
> 2. [api令牌](https://dash.cloudflare.com/profile/api-tokens) 创建令牌 - 使用模板： Workers AI (Beta)
>    就可以了。
> 
> 你要使用其他模型：[去这里](https://developers.cloudflare.com/workers-ai/models/)选择你要使用的模型，点击进去，查看到他完整的模型名称 填入one api就好了

🙏, 成功了
