### ISSUE TITLE
未使用yam配置文件的支持图床上传疑问

### ISSUE THREAD

**Issue by igeekbb** [MartialBE/one-api#155]
**例行检查**
如果要支持图床上传，是不是一定要用 config.yam 配置文件了？UI上不能设置吗？

**功能描述**

**应用场景**

**Comment by MartialBE** [comment]
不使用配置文件 
可以使用环境变量来配置。

如果你同时在docker设置了环境变量 并且设置了配置文件。那么环境变量会覆盖配置文件的设置

**Comment by MartialBE** [comment]
UI不可以
因为我觉得像 图床 消息通知这些配置应该是常量配置。应该在程序启动前先配置好。
所以就没写后台UI动态配置

**Comment by MartialBE** [comment]
对了 如果要使用图床 推荐使用 imgur
smms sd3生成容易触发 图片检测 上传失败。

**Comment by igeekbb** [comment]
> 对了 如果要使用图床 推荐使用 imgur smms sd3生成容易触发 图片检测 上传失败。

我注意到部署页面的环境变量还未添加，另在更新介绍里也只需要填写“imgur设置：STORAGE_IMGUR_CLIENT_ID”，而不需要Client secret:客户端密码吗？

**Comment by MartialBE** [comment]
wiki还没更新
是的 只要client id 就好了。

**Comment by woodchen-ink** [comment]
> 不使用配置文件 可以使用环境变量来配置。
> 
> 如果你同时在docker设置了环境变量 并且设置了配置文件。那么环境变量会覆盖配置文件的设置

在docker下怎么使用配置文件....

**Comment by MartialBE** [comment]
https://github.com/MartialBE/one-api/wiki/Deployment#使用-docker-compose-进行部署

**Comment by woodchen-ink** [comment]
> [https://github.com/MartialBE/one-api/wiki/Deployment#使用-docker-compose-进行部署](https://github.com/MartialBE/one-api/wiki/Deployment#%E4%BD%BF%E7%94%A8-docker-compose-%E8%BF%9B%E8%A1%8C%E9%83%A8%E7%BD%B2)

谢谢

**Comment by woodchen-ink** [comment]
> [https://github.com/MartialBE/one-api/wiki/Deployment#使用-docker-compose-进行部署](https://github.com/MartialBE/one-api/wiki/Deployment#%E4%BD%BF%E7%94%A8-docker-compose-%E8%BF%9B%E8%A1%8C%E9%83%A8%E7%BD%B2)

![image](https://github.com/MartialBE/one-api/assets/95951386/a4a04b47-f244-41e9-a0ac-9d61f9302dce)
d大佬, 麻烦问下, 我这里配置了, 为什么日志还是显示为启用tg呢
![image](https://github.com/MartialBE/one-api/assets/95951386/0db7d640-43a6-4a54-9e83-98cfb0a8484e)
其他配置都生效了

**Comment by MartialBE** [comment]
bug， 已经修复了，拉取一下最新代码
