### ISSUE TITLE
claude 发送图片缺失文本消息

### ISSUE THREAD

**Issue by an9xyz** [MartialBE/one-api#156]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

```
{
    "model": "anthropic/claude-3-opus",
    "messages": [
        {
            "role": "user",
            "content": [
                {
                    "type": "text", #缺失`text`
                },
                {
                    "type": "image_url",
                    "image_url": {
                        "url": "https://imageurlxxxx"
                    }
                }
            ]
        }
    ]
}
```
响应：
```
{
    "error": {
        "message": "Panic detected, error: interface conversion: interface {} is nil, not string. Please submit a issue here: https://github.com/MartialBE/one-api",
        "type": "one_api_panic"
    }
}
```

**复现步骤**

**预期结果**
claude 多模态模型支持只传图片不传消息

**相关截图**
如果没有的话，请删除此节。

**Comment by MartialBE** [comment]
不传消息的话，为什么要携带一个空的 text类型消息呢？直接删除不就好了？

**Comment by MartialBE** [comment]
就算是 官方接口也不支持这样写：
<img width="1048" alt="iShot_2024-04-19_15 51 33" src="https://github.com/MartialBE/one-api/assets/42402987/d6f96935-968e-4660-897e-af6c7ccc9807">
<img width="1242" alt="iShot_2024-04-19_15 52 37" src="https://github.com/MartialBE/one-api/assets/42402987/7695382b-6166-40c3-bc49-e33cd3f6b2c3">

**Comment by an9xyz** [comment]
> 不传消息的话，为什么要携带一个空的 text类型消息呢？直接删除不就好了？

使用原版one-api可以请求成功，或者说应该剔除掉第一个空元素

**Comment by MartialBE** [comment]
我觉得 应该要符合api请求规范吧。
不能因为错误的api格式而去让服务端这边去修复吧。
你可以说这个报错不应该抛出Panic错误。可以显示更加友好的错误信息。
