### ISSUE TITLE
fastgptV4.7.1报：Unexpected token c in JSON at position 0  错误

### ISSUE THREAD

**Issue by zaite** [MartialBE/one-api#157]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
fastgptV4.7.1报：Unexpected token c in JSON at position 0  错误
**复现步骤**
测试以下大模型都存在这个问题：gpt-3.5-turbo 、qwen-turbo、qwen-max
**预期结果**

**相关截图**
![image](https://github.com/MartialBE/one-api/assets/22079456/5837d65e-eebd-4d68-8ee5-b748e3a113c3)
![image](https://github.com/MartialBE/one-api/assets/22079456/29e0e494-cb43-4adf-b98e-985bab345542)
![image](https://github.com/MartialBE/one-api/assets/22079456/1d942b94-3ee2-4eeb-9887-837e372251a6)

**Comment by MartialBE** [comment]
你先更新到最新版本  再看看还有没有报错 昨天的版本有问题。

**Comment by zaite** [comment]
> 你先更新到最新版本 再看看还有没有报错 昨天的版本有问题。

我今天更新的，使用的是ghcr.io/martialbe/one-api:dev镜像

**Comment by zaite** [comment]
> 我看到你的报错里面有timeout的信息 这是可能是昨天发布的版本导致的bug。5秒就会超时。
> 
> 如果最新dev还是报错的话 晚点我再看看。

我刚同步了下最新main分支，自己打了个镜像，现在重新部署后好像正常了

**Comment by MartialBE** [comment]
OK 那我先关了issue 有问题你在开
