### ISSUE TITLE
[HELP] - Feat: playground/chat page

### ISSUE THREAD

**Issue by Miraz4300** [MartialBE/one-api#159]
Hello **MartialBE**. Hope you're well. Need a small help.
I've implemented this page at /playground, which loads [ChatGPT-Next-Web](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web) as iframe. This code works at the original repository of [songquanpeng](https://github.com/songquanpeng)
[one-api](https://github.com/songquanpeng/one-api). But somehow not works on your repo and shows error message which is `In order to use playground, please create an API key or token here` . Still, I'm not good at react. Maybe it fails to retrieve API key.

just need advice how to solve it. and I appreciate your help.

**Also, I'm willing to provide full English translation of your repository, which I'm currently working from the scratch.**

```
import React, { useEffect, useState } from "react";
import { API } from 'utils/api';
import { showError } from 'utils/common';
import { Typography } from "@mui/material";
import SubCard from "ui-component/cards/SubCard";
import { Link } from "react-router-dom";
import { useSelector } from 'react-redux';

const Playground = () => {
  const [value, setValue] = useState([]);
  const [isLoading, setIsLoading] = useState(true);

  const loadTokens = async () => {
    setIsLoading(true);
    const res = await API.get(`/api/token/?p=0`);
    const { data } = res.data;
    setValue(data);
    setIsLoading(false);
  };

  useEffect(() => {
    loadTokens();
  }, []);

  if (isLoading) {
    return <SubCard title="Playground">
    <Typography align="center">Loading...</Typography></SubCard>;
  } else if (value.length) {
    const siteInfo = useSelector((state) => state.siteInfo);
    const chatLink = siteInfo.chat_link + `#/?code=112233&settings={"key":"sk-${value[0]?.key}","url":"${siteInfo.server_address}"}`;
    return (
      <iframe
        src={chatLink}
        style={{ width: "100%", height: "85vh", border: "none" }}
      />
    );
  } else {
    showError("Failed to load playground. Please create a Token/API key first.");
    return <SubCard title="Playground">
      <Typography align="center">In order to use playground, please create an API key or token <Link to="/panel/token">here</Link></Typography></SubCard>;
  }
};

export default Playground;

```

**Comment by MartialBE** [comment]
My API response structure is different from songquanpeng's, as it includes pagination information. Here is the structure:

```json
{
  "data": {
    "data": [
      ...
    ],
    "page": 1,
    "size": 10,
    "total_count": 20
  },
  "message": "",
  "success": true
}
```

Therefore, to access the data, you should write it like this:

```js
const { data } = res.data.data;
```

This way, you can retrieve the data you need. I hope this helps. Feel free to ask if you have any other questions.

Lastly, thank you for liking this project. I look forward to your PR with the English translation.
