### ISSUE TITLE
azure的模型需要手动映射吗？

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-api#16]
我发现azure的部署名称没有像原项目那样自动映射，是有什么考虑吗？

**Comment by woodchen-ink** [comment]
比如 gpt-3.5-turbo，没有自动映射到gpt-35-turbo

一个是手动映射挺麻烦，还有一个是前端展示可用模型的话，也会同时展示gpt-35-tubo了，感觉有点奇怪

**Comment by MartialBE** [comment]
因为之前项目添加了大量的if判断语句。
我觉得这些可以使用现有的map功能实现就没有做这个处理了。
不过你这样说确实存在合理性。后面我看看可以针对azure处理，如果没有存在map映射并且模型名称存在 . 就将 . 移除掉。

**Comment by woodchen-ink** [comment]
你是真牛，过年熬夜搞代码，不富你富谁
