### ISSUE TITLE
调用command+ API报错

### ISSUE THREAD

**Issue by Arthur-WWW** [MartialBE/one-api#160]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [X] 我已确认目前没有类似 issue
+ [X] 我已确认我已升级到最新版本
+ [X] 我已完整查看过项目 README，尤其是常见问题部分
+ [X] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [X] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
配置command+后通过双语书那个程序调用API进行翻译会得到下面的报错
Provider API error:
invalid request: all elements in history must have a message.

配置的groq执行同样的操作运行正常，Gemini也会报400错误，不过Gemini上游有个open的issue，command+上游并没有支持所以来这儿提issue了。

**Comment by MartialBE** [comment]
看这个报错信息，应该是你使用程序调用api时传入了空消息导致的。
你应该去你使用的程序作者那边询问一下看看。

**Comment by Arthur-WWW** [comment]
同一个程序完全一样的调用方法，调用配置的groq和deepseek都运行正常，也可能是command+那边做了什么限制，因为调用Gemini也有问题，但直接调Gemini的接口没有问题

Buer ***@***.***> 于 2024年4月21日周日 15:20写道：

**Comment by MartialBE** [comment]
你可以贴出 程序传入的 api参数吗？

**Comment by Arthur-WWW** [comment]
model: gpt-3.5-turbo
messages:
[
    {'role': 'system', 'content': ''},
    {
        'role': 'user',
        'content': 'Please help me to translate,`Hello World` to simplified chinese, please return only translated
content not include the origin text'
    }
]
temperature: 1.0

下面这行代码就报错了
completion = self.openai_client.chat.completions.create(
            model=self.model,
            messages=messages,
            temperature=self.temperature,                                  )

**Comment by MartialBE** [comment]
是因为：`{'role': 'system', 'content': ''},`
command+ 不支持空消息

**Comment by MartialBE** [comment]
而且 为什么没有 `system`提示，却要传入一个空消息进来。除了会增加`prompt_tokens`好像没有任何作用吧？
还是有什么我不知道的用法？
<img width="761" alt="iShot_2024-04-21_21 35 59" src="https://github.com/MartialBE/one-api/assets/42402987/f5cb68df-c3ee-4bce-a234-553d29939799">
<img width="783" alt="iShot_2024-04-21_21 36 20" src="https://github.com/MartialBE/one-api/assets/42402987/b5c9e205-c858-44c0-ac43-1dbc94804d62">

**Comment by Arthur-WWW** [comment]
我用的双语书程序也是个开源项目https://github.com/yihong0618/bilingual_book_maker，它应该是同时支持带system也可以不带system提示两种使用方法，那我尝试自己改下代码，不传system提示试试，那Gemini很可能也是这个原因，我测试一下，谢谢

**Comment by Arthur-WWW** [comment]
经过测试确实是这个原因，不传空的system提示后，部署的command+和Gemini都可以正常使用了，太感谢了

**Comment by MartialBE** [comment]
嗯嗯，翻译文章书籍，推荐还是写一个好的`system prompt`，不然直接让他翻译，翻译的好差...

**Comment by Arthur-WWW** [comment]
是的，测试时为了简化用这个项目默认的prompt，真正翻译时用了一个按照https://github.com/EmbraceAGI/LangGPT 这个模板写的比较长的prompt，不过我只放在user里，没有用system
