### ISSUE TITLE
日志中消费显示倍率异常

### ISSUE THREAD

**Issue by myvica** [MartialBE/one-api#161]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
检查了模型价格设置没问题，为`$0.0026 / ￥0.0182`，但消费后日志中记录的倍率不是`$0.0026`而是`$0.0026000000000000003`
**复现步骤**
`claude-3-sonnet-20240229`模型消费后在日志里记录的就是这个奇怪的价格
**预期结果**
正常日志应该是
> 模型费率 $0.0026/1k (输入) | $0.0078/1k (输出)，分组倍率 1.00

**相关截图**
![Pin_2024-04-22_17-22-58](https://github.com/MartialBE/one-api/assets/131929457/faf4a076-41fa-4557-a448-5527d2549364)

**Comment by MartialBE** [comment]
已修复 等action编译完成后 重新拉取dev镜像
