### ISSUE TITLE
Azure Speech转tts报错404

### ISSUE THREAD

**Issue by SuiYunsy** [MartialBE/one-api#164]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
# 配置如下：
![image](https://github.com/MartialBE/one-api/assets/104718844/11061cf9-160b-418e-8e0c-e0829b87148f)
![image](https://github.com/MartialBE/one-api/assets/104718844/dbdd9351-2e9a-48b6-943d-2e8210bf7c43)

# 调用方式：
```py
from pathlib import Path
from openai import OpenAI
client = OpenAI(
    api_key="sk-oneapi令牌",
    base_url="https://oneapi地址/v1",
)

speech_file_path = Path(__file__).parent / "speech.mp3"
response = client.audio.speech.create(
  model="tts-1",
  voice="echo",
  input="跨云和混合环境部署 Windows 和 Linux 虚拟机，实现应用程序的现代化并开发应用。"
)

response.stream_to_file(speech_file_path)
```

# 调用程序后日志报错：
`relay error (channel #2(AzTTS)): Provider API error: bad response status code 404`
`404 POST /v1/audio/speech`

# 我用Azure官方的调用示例是正常的：
```py
'''
  For more samples please visit https://github.com/Azure-Samples/cognitive-services-speech-sdk 
'''

import azure.cognitiveservices.speech as speechsdk

# Creates an instance of a speech config with specified subscription key and service region.
speech_key = "我的key"
service_region = "westeurope"

speech_config = speechsdk.SpeechConfig(subscription=speech_key, region=service_region)
# Note: the voice setting will not overwrite the voice element in input SSML.
speech_config.speech_synthesis_voice_name = "zh-CN-XiaochenMultilingualNeural"

text = "跨云和混合环境部署 Windows 和 Linux 虚拟机，实现应用程序的现代化并开发应用。"

# use the default speaker as audio output.
speech_synthesizer = speechsdk.SpeechSynthesizer(speech_config=speech_config)

result = speech_synthesizer.speak_text_async(text).get()
# Check result
if result.reason == speechsdk.ResultReason.SynthesizingAudioCompleted:
    print("Speech synthesized for text [{}]".format(text))
elif result.reason == speechsdk.ResultReason.Canceled:
    cancellation_details = result.cancellation_details
    print("Speech synthesis canceled: {}".format(cancellation_details.reason))
    if cancellation_details.reason == speechsdk.CancellationReason.Error:
        print("Error details: {}".format(cancellation_details.error_details))
```

不知道还要补充哪些细节，希望作者大大可以看看是哪里的问题😂

**Comment by MartialBE** [comment]
你把`https://westeurope.api.cognitive.microsoft.com/`改成 `https://westeurope.tts.speech.microsoft.com`

这里确实有点误解。到时候我改简单点，只要输入地区，不需要输入完整的api地址。

**Comment by SuiYunsy** [comment]
好的，修改URL后就可以了，谢谢！

**Comment by MartialBE** [comment]
改了一下，之后只要输入地区就好了。
已在dev镜像更新

**Comment by SuiYunsy** [comment]
> 改了一下，之后只要输入地区就好了。 已在dev镜像更新

使用最新的v0.8.0版本，在windows本机本地新启动程序，尝试添加az speech，发现点不动提交😂
![image](https://github.com/MartialBE/one-api/assets/104718844/66ee0825-ee27-48ee-8cb9-6bb39876fcec)
![image](https://github.com/MartialBE/one-api/assets/104718844/10aa7d50-209a-42fe-90ea-4047c9e1e1e9)
这个提交按钮点不动，后台log也没反应。但是添加其他渠道是正常的。

**Comment by MartialBE** [comment]
emmm 忘记把url的必填给去除了。 已经修复
