### ISSUE TITLE
缓存响应前判断是否正常返回

### ISSUE THREAD

**Issue by zcf0508** [MartialBE/one-api#167]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

缓存响应前判断是否正常返回

**应用场景**

部分三方接口异常时不报错，而是返回空的响应，这时如果开启了缓存会缓存空响应。
预期是如果返回的是空响应就不缓存。

**Comment by MartialBE** [comment]
他这个空响应是 什么输出都没有 还是 有输出正确的结构，但是内容为空？

**Comment by MartialBE** [comment]
我做了一层处理， 如果是非`stream`，返回的消息内容为空 则不会缓存。 
如果在`stream`下，有报错 则不会缓存。但是返回200，输出结构正确时，还是会缓存。
目前不好检测`stream`返回正确结构时，判断内容是否为空。

**Comment by MartialBE** [comment]
有需求可以自己拉取先进行编译，GitHub Actions 的`Ubuntu`镜像出问题了，现在无法编译，需要等GitHub修复

**Comment by zcf0508** [comment]
![image](https://github.com/MartialBE/one-api/assets/21942252/cac28b98-4915-4e7b-99ac-00f8aba9a9c2)

这是日志中的记录

**Comment by MartialBE** [comment]
目前只有聊天和补全有缓存， 我加了一个判断，如果 输出tokens == 0 的话，那么就不缓存。 这应该是可以解决这个问题了。

**Comment by zcf0508** [comment]
好的，非常感谢！
