### ISSUE TITLE
AWS 的claude渠道   opus模型无法通过测试，其他模型没有问题

### ISSUE THREAD

**Issue by mmxzwj** [MartialBE/one-api#169]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
AWS 的claude渠道   opus模型无法通过测试，其他模型没有问题

**相关截图**
![image](https://github.com/MartialBE/one-api/assets/101969595/457672d1-6bc5-4164-b435-1904fb3dcc7e)
![image](https://github.com/MartialBE/one-api/assets/101969595/4b5e9c27-00d8-4ba8-bb53-8b8c64d54262)

如果没有的话，请删除此节。

**Comment by MartialBE** [comment]
因为写的时候`aws`还没`opus`模型，所有没有做映射，已经添加了， 
你拉取dev镜像就好了。 
或者你也可以直接填写`aws`中 `opus`真实的模型名称：`anthropic.claude-3-opus-20240229-v1:0`，使用这个名称请求
