### ISSUE TITLE
透传报错信息

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-api#171]
有个朋友, 调用openai的内容审核接口, 模型是对的, 接口url错了,是 `/v1/completions`.

因为我也没用过内容审核模型, 所以一直以为是权限问题. 

请问报错的时候,可以把openai的报错透传过来吗

**Comment by MartialBE** [comment]
一直都有透传的。针对每个供应商的报错，都会返回他们的错误信息。
<img width="624" alt="iShot_2024-04-25_20 52 25" src="https://github.com/MartialBE/one-api/assets/42402987/9568e7f3-61ec-4adb-8ec7-32636956667d">

**Comment by woodchen-ink** [comment]
奇怪了, 我使用的官方openai, 只会报权限错误
![ff7accf0-9085-41f6-92a1-d4c3c2e933d8](https://github.com/MartialBE/one-api/assets/95951386/7e84cc29-9341-44fd-af8f-e8eb666f0ed8)

**Comment by woodchen-ink** [comment]
请问这部分的代码在哪里? 我比对下看看是不是我这里的残留问题

**Comment by MartialBE** [comment]
当你看到`Provider API error:`开头的错误信息，说明就是供应商接口错误信息，如果供应商的错误信息解析不出来，那么`Provider API error:`的内容是请求返回的错误代码。

**Comment by MartialBE** [comment]
Yes 这里就是OpenAI返回的错误信息

**Comment by MartialBE** [comment]
错误处理的代码：
https://github.com/MartialBE/one-api/blob/58a0b6f9bc7527c68ea9cc000da7229a48ff81b5/common/requester/http_requester.go#L189


`HttpErrorHandler` 是每个供应商的API错误处理函数

**Comment by woodchen-ink** [comment]
> 看你的输出 是请求了两次吧

调用了几次这个我倒不清楚, 因为是她自己去调用的.   我去看docker日志也是"svip下无可用模型", 所以才以为是权限问题. 

我明白了, 谢谢哈

**Comment by woodchen-ink** [comment]
> "svip下无可用模型",说明你渠道那里没有配置这个模型。一般内容审核模型是没有配置的。当你请求`/v1/moderations`时如果没有传入model，那么会自动设置为`text-moderation-stable`

模型权限应该是有的, 只是好像有几种报错, 都会额外带一条: "xxx 下无可用模型", 我下次碰到截图给你看看

**Comment by woodchen-ink** [comment]
![image](https://github.com/MartialBE/one-api/assets/95951386/766e5383-7ff1-440b-8389-d8fd502163a4)
这里一直是这样配置的

**Comment by MartialBE** [comment]
"xxx 下无可用模型" 这个情况是第一步找模型的时候报的错。
遇到这个错误 你要查看 这个分组下 有没有对应的模型存在
