### ISSUE TITLE
Claude模型调用404，能修复吗

### ISSUE THREAD

**Issue by pigsns** [MartialBE/one-api#173]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
客户端调用Claude模型提示404,

**复现步骤**
生成token令牌，客户端调用 Claude模型，报404

**预期结果**
正常调用Claude大模型

**相关截图**
{
  "error": {
    "status": 404,
    "headers": {
      "cache-control": "max-age=604800",
      "connection": "keep-alive",
      "content-encoding": "gzip",
      "content-length": "103",
      "content-type": "application/json; charset=utf-8",
      "date": "Tue, 30 Apr 2024 02:36:17 GMT",
      "server": "nginx",
      "vary": "Accept-Encoding",
      "x-oneapi-request-id": "20240430103617822401442bsPhzupx"
    },
    "error": {
      "error": {
        "code": "",
        "message": "Invalid URL (POST /v1/messages)",
        "type": "invalid_request_error"
      }
    }
  },
  "endpoint": "https://openai.pp****hu.net/",
  "provider": "anthropic"
}
如果没有的话，请删除此节。

**Comment by MartialBE** [comment]
你需要使用OpenAI客户端调用。
请求的地址应该是`/v1/chat/completions` 而不是`/v1/messages`
