### ISSUE TITLE
按次数计费好像无效

### ISSUE THREAD

**Issue by Jack-loong** [MartialBE/one-api#174]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
修改模型计费模式为按次数计费后，按照token倍率计费，好像无效？
**复现步骤**
模型价格->修改一个模型的计费类型->按次收费（没有看到有修改单次计费价格）->使用这个模型->查看日志
**预期结果**
1. 可以指定模型单次计费的单次价格。
2. 每调用一次模型可以按照单次价格进行计费。
**相关截图**
如果没有的话，请删除此节。

**Comment by MartialBE** [comment]
1. 模型选择`按次计费`时，你只需要配置 `输入倍率` 即可。 `输出倍率`可以随便填。
2. 逆选择`按次计费`后， 就是每调用一次，按照你设置的`输入倍率`计费。 你可以查看日志中的详情，详情里面会写 `模型费率 $xxx/次，分组倍率 xxx`
