### ISSUE TITLE
希望增加从one-api迁移的说明

### ISSUE THREAD

**Issue by ZeroDeng01** [MartialBE/one-api#177]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
希望从one-api原版迁移到MartialBE/one-api版本有相关的说明吗（MYSQL+Docker），比如那些数据表直接迁移，那些数据需要整理后迁移，因为渠道数据、令牌等比较多，重新部署手动一个一个处理比较麻烦容易出错！如果可以提供一个迁移相关工具最好了！工具不方便的话看是否能有一个表结构对比迁移说明！谢了！

**应用场景**

从one-api迁移到MartialBE/one-api

**Comment by MartialBE** [comment]
最好是重新添加。因为表结构有变化 并且后面新加的渠道key的存储设置对应的字段也不一致。
渠道的type值也是不一样的。

如果你的渠道只是openai的话 可以尝试把原有的数据对应相同的字段导入进去。

**Comment by ZeroDeng01** [comment]
好的，那我重新跑一套

**Comment by ZeroDeng01** [comment]
> 最好是重新添加。因为表结构有变化 并且后面新加的渠道key的存储设置对应的字段也不一致。
> 渠道的type值也是不一样的。
> 
> 如果你的渠道只是openai的话 可以尝试把原有的数据对应相同的字段导入进去。
> 
> 

好的，那我重新跑一套，谢啦
