### ISSUE TITLE
感谢作者的开源，请问是否考虑增加docker一键更新到最新版的功能

### ISSUE THREAD

**Issue by Akuns** [MartialBE/one-api#178]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
感谢作者的开源，请问是否考虑增加docker一键更新到最新版的功能，太需要了。这样能实时更新到最版本，体验最新功能和修复bug
**应用场景**

**Comment by MartialBE** [comment]
在你的终端中，输入`docker ps`, 查看你需要更新的容器名称:
<img width="1201" alt="iShot_2024-05-09_20 51 57" src="https://github.com/MartialBE/one-api/assets/42402987/3bc3fd86-90b5-4e80-aa69-d80583f3bc51">

如果你使用我[wiki](https://github.com/MartialBE/one-api/wiki/Deployment#docker-%E9%83%A8%E7%BD%B2)的命令的话，那么你的容器名称应该是`one-api`。

如果你的容器名称不叫`one-api`， 请将下面命令中的`one-api`修改成你自己的名称

1. 手动更新
手动执行后，会直接升级，和原版`one-api`的命令一致
```bash
docker run --rm --name watchtower -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --cleanup --run-once one-api
```

2. 自动更新
执行后，每天3点会自动检测是否需要升级。

```bash
docker run -d \
    --name watchtower \
    -e TZ=Asia/Shanghai \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower --cleanup --schedule "0 0 3 * * *" one-api

```
如果你需要更改检测时间，请修改`0 0 3 * * *`，可自己去查询`Cron表达式`的写法
```
 ┌──────────── [可选] 秒 (0 - 59)
            | ┌────────── 分钟 (0 - 59)
            | | ┌──────── 小时 (0 - 23)
            | | | ┌────── 天数 (1 - 31)
            | | | | ┌──── 月份 (1 - 12)
            | | | | | ┌── 星期几 (0 - 6, 星期天 = 0)
            | | | | | |
            * * * * * * 命令
```

**Comment by MartialBE** [comment]
这个方法同样适用于其他容器。
至于直接后台一键升级的话，暂时没有这个计划。
定时自动升级的话，要注意，有时候可能会有破坏性更新，可能会有些问题。最好还是 自己查看完更新内容后再手动升级比较好。

**Comment by Akuns** [comment]
> 在你的终端中，输入`docker ps`, 查看你需要更新的容器名称: <img alt="iShot_2024-05-09_20 51 57" width="1201" src="https://private-user-images.githubusercontent.com/42402987/329250540-3bc3fd86-90b5-4e80-aa69-d80583f3bc51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMDgzNjUsIm5iZiI6MTcxNTMwODA2NSwicGF0aCI6Ii80MjQwMjk4Ny8zMjkyNTA1NDAtM2JjM2ZkODYtOTBiNS00ZTgwLWFhNjktZDgwNTgzZjNiYzUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDAyMjc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NGQwZjVkNTk4Y2U2MzczN2NjNDlkZGM4ZDExODZkNWVjZWFmZDVmNGJlNzUxODk2MTViODU4YTAwOGE5MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nSiRQ6bDC406MSUiGAZOClwu1520Yv2UPZi55lJwuBc">
> 
> 如果你使用我[wiki](https://github.com/MartialBE/one-api/wiki/Deployment#docker-%E9%83%A8%E7%BD%B2)的命令的话，那么你的容器名称应该是`one-api`。
> 
> 如果你的容器名称不叫`one-api`， 请将下面命令中的`one-api`修改成你自己的名称
> 
> 1. 手动更新
>    手动执行后，会直接升级，和原版`one-api`的命令一致
> 
> ```shell
> docker run --rm --name watchtower -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --cleanup --run-once one-api
> ```
> 
> 2. 自动更新
>    执行后，每天3点会自动检测是否需要升级。
> 
> ```shell
> docker run -d \
>     --name watchtower \
>     -e TZ=Asia/Shanghai \
>     -v /var/run/docker.sock:/var/run/docker.sock \
>     containrrr/watchtower --cleanup --schedule "0 0 3 * * *" one-api
> ```
> 
> 如果你需要更改检测时间，请修改`0 0 3 * * *`，可自己去查询`Cron表达式`的写法
> 
> ```
>             ┌──────────── [可选] 秒 (0 - 59)
>             | ┌────────── 分钟 (0 - 59)
>             | | ┌──────── 小时 (0 - 23)
>             | | | ┌────── 天数 (1 - 31)
>             | | | | ┌──── 月份 (1 - 12)
>             | | | | | ┌── 星期几 (0 - 6, 星期天 = 0)
>             | | | | | |
>             * * * * * * 命令
> ```

哇，感谢大佬，教程回复得真详细，已成功更新！谢谢🙏
