### ISSUE TITLE
计算token和上游显示的不一样

### ISSUE THREAD

**Issue by mmxzwj** [MartialBE/one-api#179]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
接的中转是newapi搭建的,使用时发现自己的网站统计token和上游不一样，不清楚是哪里的问题。
**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/MartialBE/one-api/assets/101969595/c1fe8796-47a4-454d-8ae9-167f25119333)
图一是上游统计图
![image](https://github.com/MartialBE/one-api/assets/101969595/206c8ec8-98b6-4be9-879c-dcb8d8956850)
图二是自己搭建的newapi网站
![image](https://github.com/MartialBE/one-api/assets/101969595/1d6532e4-3c24-42f5-b829-96fb69502506)

如果没有的话，请删除此节。

**Comment by mmxzwj** [comment]
![image](https://github.com/MartialBE/one-api/assets/101969595/7b95c951-4689-4682-bdfd-bf4f3154aa94)
![image](https://github.com/MartialBE/one-api/assets/101969595/79db5408-027e-4403-bc0f-cc338516e583)
图片传错了

**Comment by MartialBE** [comment]
因为`OpenAI`的流模式下 是不会返回 你使用的`tokens`，所以`tokens`是由程序自己计算出来的。
而`Claude`的流模式下 是会返回 你使用的`tokens`，所以他的`tokens`是跟官方一样的。

这就会导致一个问题：
上游： 接入`Claude`，他在计费时，使用了官方返回的`tokens`，所以计费是正确的。
下游： 使用的是`OpenAI`接入上游，所以是程序自己计算，肯定和上游的`tokens`不一致。
如果你上下游都使用 `OpenAI`的模型或者非流模式下，那是一致的。

至于 你说的 你自己搭建的`new-api` 能够和上游一致，我没有模拟出来：

1. 上游是原版`one-api`，下游`new-api`

上游日志：
<img width="1139" alt="iShot_2024-05-12_17 18 22" src="https://github.com/MartialBE/one-api/assets/42402987/41bed7bc-3b2a-431f-a314-74bb04d73959">

下游日志：
<img width="1242" alt="iShot_2024-05-12_17 18 06" src="https://github.com/MartialBE/one-api/assets/42402987/fd4ca589-89bb-4639-882e-802babb1a876">

2. 上游是`new-api`，下游`new-api`
上游日志：
<img width="1234" alt="iShot_2024-05-12_17 22 36" src="https://github.com/MartialBE/one-api/assets/42402987/96716f20-c26f-46b3-8b50-992ada2fe15d">


下游日志：

<img width="1243" alt="iShot_2024-05-12_17 22 24" src="https://github.com/MartialBE/one-api/assets/42402987/e7b5f705-9d92-4b81-8add-6cd5ce81ce94">
