### ISSUE TITLE
模型映射在计费和统计时是否应该按照映射前的模型计算

### ISSUE THREAD

**Issue by soulgod001** [MartialBE/one-api#181]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
当我将gpt-3.5模型映射为azure-gpt-3.5模型时，用户使用gpt-3.5模型，但是计费和日志中均显示为azure-gpt-3.5模型。
但模型价格中并不会提示azure-gpt-3.5模型未设置价格。
**复现步骤**

**预期结果**
计费和日志均应该按照映射前的模型。
**相关截图**
![image](https://github.com/MartialBE/one-api/assets/32891255/63de625a-6b5f-4647-a62a-dca509e7cded)
![1715512300894](https://github.com/MartialBE/one-api/assets/32891255/5934fb97-89f6-491d-b4b8-b4b8ffae9f04)
![1715512395333](https://github.com/MartialBE/one-api/assets/32891255/fa0c333b-ad54-4c98-9d2a-ef0d6255677f)

**Comment by MartialBE** [comment]
1. 价格模型没有显示 的问题： 现在只会检测你在渠道模型中填写的模型。并不会检测你在模型映射中填写的模型。 

2. 模型映射的问题： 我之前也考虑过这个问题， 但是后面想了一下，模型映射的作用： 使一些通用模型名称能够映射到版本模型中。
openai也是这样处理的。当你直接使用gpt-4时， 你会发现openai给你返回的是模型名称是带有版本号的。 而不同的版本号也是不同的定价。反映在用户日志中也应该是实际请求的模型价格。

**Comment by soulgod001** [comment]
了解了，感谢大佬回复。
