### ISSUE TITLE
能否将可用模型页面给普通用户展示

### ISSUE THREAD

**Issue by soulgod001** [MartialBE/one-api#182]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
能否将可用模型暴露给普通用户，以便于普通用户自行了解当前的各模型价格？
还有MJ页面能否在没有对应渠道时自动隐藏？
**应用场景**
用户可以自己追踪当前所有模型的价格。

**Comment by MartialBE** [comment]
`可用模型`就是暴露给普通用户的，普通用户是可以查看的。
这个`MJ`页面显示的问题后续再改
