### ISSUE TITLE
自动获取models并定时更新

### ISSUE THREAD

**Issue by KarlLee830** [MartialBE/one-api#183]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

填入渠道地址后，填写模型时，能否直接获取渠道地址的models填入模型列表？并且能否定时自动更新？

**Comment by MartialBE** [comment]
这个自动获取 模型列表 的功能，后续再加吧。
自动更新 应该不会做，自动更新完，有新模型的话，那么应该要去增加 模型价格，不然价格是错误的。

**Comment by myvica** [comment]
自动更新没什么必要，模型很少经常变动的

**Comment by woodchen-ink** [comment]
+1 
自动获取 模型列表 很方便

并且当渠道类型为“自定义”时，可以在模型处添加一个“刷新图标”，点击后自动重新获取模型列表并填充

下面这个已经实现了，虽然很简单，但是也能参考下
https://github.com/ai365vip/chat-api/releases/tag/v0.4.2

（最近没咋关注，大佬还在更新👍）
