### ISSUE TITLE
渠道能否显示为渠道名称而非id

### ISSUE THREAD

**Issue by soulgod001** [MartialBE/one-api#184]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
1.渠道能否显示为渠道名称而非id
2.数据库中同时存储了用户id和用户名，当用户修改名称时日志中的用户名不会变更。
是否应该禁止修改用户名，且展示名称目前没有任何地方会显示均显示为用户名。
3.当消耗额度为0时货币符号丢失
4.由于精度问题，额度会和模型价格存在一定差异。
5.当模型价格设置为0时，模型价格显示、日志显示、额度结算均正常，但是在可用模型中会显示为默认价格。

本来想看着能不能自己改一下1但是发现数据的处理是在前端完成的，因为不会前端所以没办法自己改了。

**相关截图**
![image](https://github.com/MartialBE/one-api/assets/32891255/210517e5-85d7-4c8c-98bc-2607e68ea753)
![image](https://github.com/MartialBE/one-api/assets/32891255/b7ddacdd-c357-421f-87bc-49284b4db1ed)
![1715693040040](https://github.com/MartialBE/one-api/assets/32891255/c76202e3-c4cb-4160-85a0-00e2260d2ad5)

**Comment by MartialBE** [comment]
1. 后面我联表查一下，可以解决
2. 是的，因为原版的`one-api`设计时，日志中的用户名是直接存入数据库中的，如果要解决这个问题，最快的方法就是禁止用户修改用户名。
3. 写死在前端的，到时候改一下。
4/5 后续修复

这几天可能没时间，等下周我统一修复吧，也欢迎pr

**Comment by MartialBE** [comment]
0.8.5修复
