### ISSUE TITLE
渠道新增仅聊天选项太棒了，有个小问题

### ISSUE THREAD

**Issue by igeekbb** [MartialBE/one-api#186]
**例行检查**
渠道新增仅聊天太及时了！
最近在用chat2api项目，正好可以把免费的gpt-4o接入oai使用，但是在密钥处填写 accessToken，因为太长而出错，不知道有没有什么好的办法解决

**功能描述**
![CleanShot 2024-05-15 at 19 50 06@2x](https://github.com/MartialBE/one-api/assets/154116268/675c8bdb-1ccb-45b2-b4ef-947ae542c955)

**应用场景**

**Comment by MartialBE** [comment]
晚点 我改一下key的字段类型。

**Comment by MartialBE** [comment]
可以了，等0.8.6打包完成
