### ISSUE TITLE
请求完善价格json

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-api#189]
![image](https://github.com/MartialBE/one-api/assets/95951386/9f9271ac-4476-4b2b-9764-c7b2e6c7fbc4)

这些是通过“自动获取支持模型”添加的模型，好像还没配置价格

--- 

存在未配置价格的模型，请及时配置价格：command-light-nightly, mistral-small-2402, command, open-mixtral-8x22b-2404, mistral-medium, mistral-small, gpt-3.5-turbo-instruct-0914, coze-7360037703448117264, mistral-tiny, mistral-tiny-2312, gemini-1.0-pro-vision-001, gpt-4-1106-vision-preview, command-light, mistral-small-2312, mistral-large-2402, mistral-medium-2312,

**Comment by MartialBE** [comment]
这个不会写进去。这些都是带版本的模型。都有通用的模型名称映射它们。 后期也会过期。维护太麻烦。
如果需要的话，自己可以去编辑。

**Comment by woodchen-ink** [comment]
那如果我不设置价格，价格会出错吗

**Comment by MartialBE** [comment]
不会 会直接按30的倍率计费
