### ISSUE TITLE
主从部署时，新增模型，从节点报错

### ISSUE THREAD

**Issue by an9xyz** [MartialBE/one-api#191]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
渠道增删改之后都会调用ChannelGroup.Load()，仅master节点，slave节点只有启动时才会调用一次

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by MartialBE** [comment]
已修复，可以拉取dev镜像测试一下。
注意：新增/修改渠道，模型价格时，请在主服务器上修改，从服务器会按照你设置的同步时间进行同步。
不要直接在从服务器上修改，否则主服务器不会进行同步。

**Comment by an9xyz** [comment]
为什么不建议使用Redis，目前用最新版同步好像还有问题 @MartialBE

**Comment by cheermao** [comment]
当前我也部署了主从模式，两台机器，然后通过 nginx 负载。
从节点并未设置 FRONTEND_BASE_URL。
定位上主、从的身份是等价的，起到多节点并发。

当前root 进行渠道新增的时候，主节点会存在无法加载新的渠道，原因就是实际应该在从节点进行了配置。
通过查询#191变更。

```
func SyncChannelCache(frequency int) {
	// 只有 从 服务器端获取数据的时候才会用到
	if config.IsMasterNode {
		logger.SysLog("master node does't synchronize the channel")
		return
	}
	for {
		time.Sleep(time.Duration(frequency) * time.Second)
		logger.SysLog("syncing channels from database")
		model.ChannelGroup.Load()
		relay_util.PricingInstance.Init()
	}
}
```

是否可以注释以下内容，这样主节点也就可以定时刷新渠道信息。
```
	if config.IsMasterNode {
		logger.SysLog("master node does't synchronize the channel")
		return
	}

```
> 已修复，可以拉取dev镜像测试一下。 注意：新增/修改渠道，模型价格时，请在主服务器上修改，从服务器会按照你设置的同步时间进行同步。 不要直接在从服务器上修改，否则主服务器不会进行同步。
