### ISSUE TITLE
希望可以单独给TG设置代理

### ISSUE THREAD

**Issue by coulsontl** [MartialBE/one-api#192]
如题，中转是部署在国内的；默认无法连接TG，需要通过代理去连接；希望环境变量里加个配置可以让TG的请求走代理，但是不想让所有的渠道都走代理，所以希望单独设置

**Comment by MartialBE** [comment]
后面我加一下。

**Comment by MartialBE** [comment]
已添加

**Comment by MartialBE** [comment]
你可以更新 config.yaml文件，填写`http_proxy`使用。
也可以通过环境变量 `TG_HTTP_PROXY` /`NOTIFY_TELEGRAM_HTTP_PROXY` 使用。
