### ISSUE TITLE
官网这个按钮能否去掉，感觉使用不上

### ISSUE THREAD

**Issue by candies404** [MartialBE/one-api#194]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

**复现步骤**
渠道-》操作
**预期结果**

**相关截图**
![image](https://github.com/MartialBE/one-api/assets/154443166/4a9056ca-6b1d-4855-b067-8234edcde932)

**Comment by MartialBE** [comment]
如果你用不到 可以fork代码自己删掉就好了。
