### ISSUE TITLE
支持 gpt-3.5-turbo-instruct 模型代码补全

### ISSUE THREAD

**Issue by coulsontl** [MartialBE/one-api#195]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**

在使用gpt-3.5-turbo-instruct 模型代码补全时如果经过当前OneAPI中转则一直报错
```
2024/05/19 03:18:29 request completions failed: {"error":{"code":"invalid_text_request","message":"Provider API error: field messages is required (request id: 20240519031828853895489acWdbFAG) (request id: 20240519111828709925269UxrcZ0Y1)","type":"one_api_error"}}
[GIN] 2024/05/19 - 03:18:29 | 400 |  444.616953ms |   192.168.31.16 | POST     "/v1/engines/copilot-codex/completions"

```

如果使用渠道直连则没有这个问题，比如我用的是这个渠道 https://burn.hair

**应用场景**

vscode代码补全，参考 [override](https://github.com/linux-do/override/blob/master/main.go)

**Comment by MartialBE** [comment]
已修复 等待GitHub action编译完成后拉取dev镜像使用

docker pull ghcr.io/martialbe/one-api:dev
