### ISSUE TITLE
gemini的函数调用是不是有bug??

### ISSUE THREAD

**Issue by jqlts1** [MartialBE/one-api#197]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到
最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
gemini的函数调用似乎无法执行多步请求,比如

### 在Dify中
<img width="1239" alt="image" src="https://github.com/MartialBE/one-api/assets/17434370/fdbafd1a-5509-40ec-8b9e-506d9dee06d9">

这里确实会调用一次函数,但是对于稍微复杂一点的问题,就无法执行了 

###  我用官方api测试(openai官方,非中转)
<img width="1092" alt="image" src="https://github.com/MartialBE/one-api/assets/17434370/438ba5bf-9b0c-492a-869e-febed1ff7487">

可以看到,官方api可以成功的调用2次函数接口

### 在langchain中的代码测试

在代码中,用langchain也会出现类似的情况,以下是代码( 你可以直接运行测试 )

```python
from langchain.tools import tool
from langchain_openai import ChatOpenAI

@tool
def add(a: int, b: int) -> int:
    """Adds a and b.

    Args:
        a: first int
        b: second int
    """
    return a + b


@tool
def multiply(a: int, b: int) -> int:
    """Multiplies a and b.

    Args:
        a: first int
        b: second int
    """
    return a * b


tools = [add, multiply]

llm = ChatOpenAI(
    openai_api_key="sk-x",xxxx
    base_url="https://xxxxxx/v1",
    model="gemini-1.5-flash-latest",
)

# 给llm绑定好工具
llm_with_tools = llm.bind_tools(tools)
query = "3 * 12是多少?然后11 + 49又是多少?"

llm_with_tools.invoke(query).tool_calls
```

返回的结果如下: ( 也就是只能执行一次 )

<img width="462" alt="image" src="https://github.com/MartialBE/one-api/assets/17434370/aef656f1-c247-4e22-84e1-20062b5d9ec5">

#### 上面的代码,用官方api(非中转)测试的结果

<img width="392" alt="image" src="https://github.com/MartialBE/one-api/assets/17434370/e5625354-cbcf-4d4c-84df-9973406a1cca">

这里可以很明显的看出来,是调用了2次

是不是你在那个for循环的时候,提前返回了?

**Comment by MartialBE** [comment]
我觉得更多是 `gemini-1.5-flash-latest` 模型的问题，我在测试中 它的函数调用能力确实没有3.5好

<br class="Apple-interchange-newline">
<img width="1262" alt="image" src="https://github.com/MartialBE/one-api/assets/42402987/e8223ba1-5e42-46eb-8602-b876c2904848">

**Comment by jqlts1** [comment]
> 我觉得更多是 `gemini-1.5-flash-latest` 模型的问题，我在测试中 它的函数调用能力确实没有3.5好
> 
> 
> 
> <br class="Apple-interchange-newline">
> 
> <img width="1262" alt="image" src="https://github.com/MartialBE/one-api/assets/42402987/e8223ba1-5e42-46eb-8602-b876c2904848">
> 
> 

我在dify中发现也是这样，提示词写好是没问题。
但是在langchain中，似乎最多只能计算一个步骤？我测了很多提示词好像结果都差不多

**Comment by MartialBE** [comment]
我编写了提示词，`gemini-1.5-flash-latest`始终只能调用2次函数，第三次死活调用不了

<img width="1279" alt="iShot_2024-05-20_02 41 40" src="https://github.com/MartialBE/one-api/assets/42402987/fac57d13-f938-4273-82e2-9190eda46592">
<img width="1205" alt="iShot_2024-05-20_02 42 08" src="https://github.com/MartialBE/one-api/assets/42402987/d880d85a-f86c-4d0f-bc83-7514346b7933">
<img width="1192" alt="iShot_2024-05-20_02 46 50" src="https://github.com/MartialBE/one-api/assets/42402987/960e3b69-0144-414a-9604-6636d8b5a31f">

**Comment by MartialBE** [comment]
昨天在测试`lobe-chat`的时候就发现了，问他热门视频，其他模型都回答出具体的视频，只有它回答的分类
![LobeChat_随便聊聊_2024-05-18 (1)](https://github.com/MartialBE/one-api/assets/42402987/48db4d1e-fff7-4316-b8c7-8d8e323bef7e)

**Comment by jqlts1** [comment]
> 昨天在测试`lobe-chat`的时候就发现了，问他热门视频，其他模型都回答出具体的视频，只有它回答的分类 ![LobeChat_随便聊聊_2024-05-18 (1)](https://private-user-images.githubusercontent.com/42402987/331894105-48db4d1e-fff7-4316-b8c7-8d8e323bef7e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNjU1ODcsIm5iZiI6MTcxNjE2NTI4NywicGF0aCI6Ii80MjQwMjk4Ny8zMzE4OTQxMDUtNDhkYjRkMWUtZmZmNy00MzE2LWI4YzctOGQ4ZTMyM2JlZjdlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDAwMzQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YTY2ODg4ZTJkOGZhMjVmMmZmMzcxOTgzZjVhOGZhODFhODE1MGNkMDRhNDRlZTExOTUyMTg1NDc3NTdjYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bT4A52vy77kqxx7qHchlocngrKrghUkypEjjo_h4efI)

你可以用我那段代码在langchain跑一下吗,因为好像在langchain中,似乎不管怎么做,他都只会调用一次,我用pro也是一样的

**Comment by MartialBE** [comment]
1. `OpenAI`可以一次性调用多个函数，也就是，你调用一次接口，`OpenAI`会在`tool_calls`中返回多个函数。
2. `gemini`只会一次调用返回一个函数。也就是，你调用一次接口，`gemini`会在`tool_calls`中返回一个函数。
你使用`langchain`的`bind_tools`调用，是只会请求**一次**接口，这就是为什么`OpenAI`会一次性执行多个函数，而`gemini`只会执行一个函数。

如果你要完善函数调用，你应该写一个完整的`agent`，将函数调用结果返回给模型，模型会判断是否需要调用下一次函数还是直接返回结果。

**Comment by MartialBE** [comment]
emmmmm， 刚刚测试了`gemini`的`functionCall` 现在可以返回多个函数了。
我改一下~

**Comment by jqlts1** [comment]
> emmmmm， 刚刚测试了`gemini`的`functionCall` 现在可以返回多个函数了。 我改一下~

谢谢你重视这个问题,辛苦了刚请你喝杯咖啡....

**Comment by jqlts1** [comment]
> emmmmm， 刚刚测试了`gemini`的`functionCall` 现在可以返回多个函数了。 我改一下~

最新版的dev可以测了吗?

**Comment by MartialBE** [comment]
可以了。试试dev

**Comment by jqlts1** [comment]
> 可以了。试试dev

刚测了,新版和旧版的gemini都不能用了... 我的key确定是没有问题,也在newapi和oneapi都测了,都没问题
不确定是不是没兼容好?

**Comment by MartialBE** [comment]
不能用？用的什么？ 有报错吗？

**Comment by MartialBE** [comment]
我测试了 lobe dify LangChain 都可以执行
