### ISSUE TITLE
公告优化

### ISSUE THREAD

**Issue by soulgod001** [MartialBE/one-api#199]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
1.能否将公告转移至控制台仪表盘顶部或修改为弹框（通过确认按钮隐藏）
原因：当公告过长时无法在弹出时间内读完且无法再次点击查看，且会短时间内遮挡登录或控制台按钮。
![1716185019276](https://github.com/MartialBE/one-api/assets/32891255/c1073025-0862-44e6-a8dc-acbfd062af79)

2.公告是否应该在登录后才显示
过早的弹出公告容易打乱用户的正常熟悉流程

3.日志中渠道在优化了显示名称后会导致充值等无渠道id的数据显示未知渠道
![1716185526254](https://github.com/MartialBE/one-api/assets/32891255/cd3af039-a6d9-43b8-803a-95593e641c86)

4.设置图站logo只是将设置图片盖在了原有logo上，页面图标仍会显示原有图标，我看了下代码Go在打包的时候会把前端代码一起打包进去，这个问题是不是没办法解决，我试了一下自己修改图标并打包但不知道哪一步出了问题前端显示未知版本，后端返回版本正常。

**Comment by MartialBE** [comment]
1. OK，我也发现这个问题了，一直没改。
2. 这个暂时不会改，因为这个很多人已经当做公开公告使用了。
3. 后面判断一下，因为渠道是可以删除的，所以遇到找不到的渠道会显示未知。
4. 请参考[makefile](https://raw.githubusercontent.com/MartialBE/one-api/main/makefile)/[linux-release.yml](https://raw.githubusercontent.com/MartialBE/one-api/main/.github/workflows/linux-release.yml) 的编译步骤。配置好REACT_APP_VERSION值。

**Comment by MartialBE** [comment]
1. 已添加 关闭按钮
3. 已修复
