### ISSUE TITLE
能否支持端点路径可选/v1

### ISSUE THREAD

**Issue by yx135** [MartialBE/one-api#201]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
部分三方免费端点路径无'v1'，有没有好的办法可以适配,或者自定义路径(目前自建中间代理进行来转发one-api请求）

**应用场景**
三方端点如：
https://api.webraft.in/freeapi/chat/completions

**Comment by MartialBE** [comment]
自定义渠道 支持更改 版本号了：
<img width="755" alt="iShot_2024-05-21_19 35 39" src="https://github.com/MartialBE/one-api/assets/42402987/ad508249-3a3b-42b8-9447-414cd607e1ec">

**Comment by yx135** [comment]
赞赞赞👍
