### ISSUE TITLE
Azure Speech 渠道没有地方填写测试模型会报错

### ISSUE THREAD

**Issue by coulsontl** [MartialBE/one-api#202]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
如题：Azure Speech 渠道没有地方填写测试模型会报错

**复现步骤**

**预期结果**

**相关截图**
<img width="1424" alt="image" src="https://github.com/MartialBE/one-api/assets/149155411/0644fc98-7526-49ba-9552-fb867b497ab2">

<img width="871" alt="image" src="https://github.com/MartialBE/one-api/assets/149155411/d193b891-c04b-4e66-8604-0505f86dbbf5">

如果没有的话，请删除此节。

**Comment by MartialBE** [comment]
测试 只能测试 chat模型。
其他模型填写了也会报错

**Comment by coulsontl** [comment]
> 测试 只能测试 chat模型。 其他模型填写了也会报错

好的，感谢佬的耐心回答；那建议把`未测试`那个按钮改为`不支持`的文案，后面那个测试按钮也可以置灰掉。

**Comment by MartialBE** [comment]
模型是否支持 维护太麻烦了，新增了 提示 `仅chat模型`
