### ISSUE TITLE
登录报错：无法保存会话信息，请重试

### ISSUE THREAD

**Issue by 704572066** [MartialBE/one-api#204]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/MartialBE/one-api/assets/23404868/31c5f9ff-b92c-47a4-9279-d1922ef1ec98)

**Comment by yue916** [comment]
我也遇到了这个问题，求教楼主怎么解决的，谢谢

**Comment by sunqb** [comment]
这个问题还存在，怎么解决的，也没有关联一下commitid

**Comment by sunqb** [comment]
解决方案：设置：session_secret。

但是配置文件里面写，如果不设置会使用随机串，看来是个问题。

**Comment by sunqb** [comment]
代码看上去没问题，但是release版本为啥就是有问题呢?

![Image](https://github.com/user-attachments/assets/fc74b8fc-9c31-4118-b9f5-adc427974f54)
