### ISSUE TITLE
bug反馈：测试某渠道时返回：Go 语言无法将一个浮点数转换为一个 int64 类型的字段，位置：OpenAIProviderChatResponse 结构体中的 created 字段

### ISSUE THREAD

**Issue by yx135** [MartialBE/one-api#206]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
测试某三方渠道时，前端界面提示：
错误：json: cannot unmarshal number 1716313435.779 into Go struct field OpenAIProviderChatResponse.created of type int64 
![屏幕截图_22-5-2024_14026_one-api-llll koyeb app](https://github.com/MartialBE/one-api/assets/120313253/d81a7023-104a-44f3-a23f-894076119504)

**复现步骤**
三方渠道信息：
URL：https://api.convoai.tech
KEY：sk-cppjulr5nxs7y9hrd9xvvq6usxjncjkk7aw6xkjdxh1po5
测试模型：gpt-3.5-turbo
**预期结果**
单独在pyhton文件中调用openai库时返回正常
********************
.py
from openai import OpenAI

client = OpenAI(
    base_url="https://api.convoai.tech/v1",
    api_key="sk-cppjulr5nxs7y9hrd9xvvq6usxjncjkk7aw6xkjdxh1po5",
)
response = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[
        {
            "role": "user",
            "content": "Hello!"
        }
    ],
)
print(response)
print(response.choices[0].message.content)
***********************
返回：
ChatCompletion(id='chatcmpl-1q5XOYFI7yDUqVQGeeIjCcLqjYIu6', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='Hi there! How can I assist you today?', role='assistant', function_call=None, tool_calls=None))], created=1716312783.982, model='gpt-3.5-turbo', object='chat.completion.chunk', system_fingerprint='fp_qKfzmqhaR4', usage=CompletionUsage(completion_tokens=10, prompt_tokens=2, total_tokens=12))
Hi there! How can I assist you today?

对比其他正常渠道和报错信息，估计是这个渠道返回的created是浮点数报错了

**Comment by yx135** [comment]
渠道问题，大佬可以不优化

**Comment by MartialBE** [comment]
等编译完成后 试试 docker pull ghcr.io/martialbe/one-api:dev

**Comment by yx135** [comment]
升级后没问题了，日志看着也正常：
![image](https://github.com/MartialBE/one-api/assets/120313253/ac8f0caf-73e3-4c48-a4fa-d8935e229835)
