### ISSUE TITLE
新增持久化DB文件，并且升级的步骤教程

### ISSUE THREAD

**Issue by 2277419213** [MartialBE/one-api#209]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
持久化DB文件，并且升级的步骤教程
**应用场景**
使用 SQLite
docker run -d -p 3000:3000 \
  --name one-api \
  --restart always \
  -e TZ=Asia/Shanghai \
  -v /home/ubuntu/data/one-api:/data \
  ghcr.io/martialbe/one-api
  部署命令是这个，升级命令不知道怎么升级，希望大佬在wiki描述一下，谢谢

**Comment by MartialBE** [comment]
https://github.com/MartialBE/one-api/issues/178#issuecomment-2102615832
