### ISSUE TITLE
一个想法，集成function call的中间件

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-api#21]
网上各种接口杂乱，方式也不统一

感觉后面可能会有开源的中间件管理，支持各种自定义方式，通过中间处理，转换为openai支持的方式

不知道作者有没有这种想法

**Comment by MartialBE** [comment]
emmm，你所说的自定义是什么形式呢？
没太理解你的意思。

**Comment by woodchen-ink** [comment]
比如下面这种接口：

https://api.52vmy.cn/

这种要接入好像都需要单独写一个中间件，有个群友写了一个这个：

``` php
<?php

$url_param = '';

// Check if 'url' parameter is present in the request body
if ($json = json_decode(file_get_contents("php://input"), true)) {
    if (isset($json['url'])) {
        $url_param = $json['url'];
    }
}

// Check if 'url' parameter is present in the URL query string
if (isset($_GET['url'])) {
    $url_param = $_GET['url'];
}

if ($url_param === '') {
    // Parameter 'url' is missing
    die(json_encode(array("error" => "Parameter 'url' is missing.")));
}

// API URL
$url = "https://api.52vmy.cn/api/video/jx?url=" . urlencode($url_param);

// Initialize cURL session
$ch = curl_init();

// Set cURL options
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HEADER, false);

// Execute cURL session
$response = curl_exec($ch);
if ($response === false) {
    // If cURL fails, output the error
    die(json_encode(array("error" => curl_error($ch))));
}

// Close cURL session
curl_close($ch);

// Output the result
echo $response;
?>
```

我刚研究了一会儿function call，有点搞不明白，自己尝试接普通的post接口总是有问题，所以想是不是都需要这种中间件。

还是我理解错误，上面网址里的接口可以直接接入

---------------
补充一点我的意思：

1、 后台把常见的get,post接口封装成function call接口
2、 前端展示function的接入方式，api地址，也就是下面图片里的内容
![image](https://github.com/MartialBE/one-api/assets/95951386/340adac5-4d45-4b5a-8b5e-0c6745fe451a)

展示也许可以是表格

| 名称 | 描述 | 请求头 | 参数 | 接口地址 | 价格 |
| --- | --- | --- | --- | --- |
| name | description | headers | properties的内容 | oneapi/v1/functioncall/name | $0.02/次 |


因为我自己都还没搞懂function call，所以也许我想的是错的

**Comment by MartialBE** [comment]
这个是属于`插件` 的功能了，我觉得不应该集成在这里面的。 
这个和API转发并没有关系。
即便有这个功能在里面，也需要软件的支持，因为每个软件调用插件的形式是不一样的，毕竟大家不可能都是是直接调用API使用的

**Comment by woodchen-ink** [comment]
好的，那我自己再琢磨琢磨
