### ISSUE TITLE
分组倍率不生效

### ISSUE THREAD

**Issue by ZeroDeng01** [MartialBE/one-api#210]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
如图设置了分组倍率后，实际倍率不生效
**复现步骤**
修改分组倍率或者修改用户分组即可
**预期结果**
token结算应该按照分组倍率进行结算
**相关截图**
![image](https://github.com/MartialBE/one-api/assets/19732560/207a8fc6-ee74-4e8f-9f81-16285dfffa1e)
![image](https://github.com/MartialBE/one-api/assets/19732560/c78be9d7-5eae-4169-aa17-823681848f79)
![image](https://github.com/MartialBE/one-api/assets/19732560/7506d1df-b5e3-410d-b17d-908fe6a17046)

如果没有的话，请删除此节。

**Comment by MartialBE** [comment]
我测试 没问题啊。
<img width="675" alt="image" src="https://github.com/MartialBE/one-api/assets/42402987/aa6276c8-5277-4a0c-a85e-25df325d690f">

**Comment by ZeroDeng01** [comment]
> 我测试 没问题啊。
> 
> <img width="675" alt="image" src="https://github.com/MartialBE/one-api/assets/42402987/aa6276c8-5277-4a0c-a85e-25df325d690f">
> 
> 

嗯，我测试过了，是我这边开启缓存的问题Thx!
