### ISSUE TITLE
render平台部署后登陆后访问其他页面网站无法加载，需要手动刷新一下，

### ISSUE THREAD

**Issue by yx135** [MartialBE/one-api#211]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
fork后利用render部署后，访问登陆进去点击左侧其他tab页面后URL会跳转，但不会加载页面内容，需要在浏览器上刷新一次才会加载
已检查如下：
1.render后台查看日志没有该页面到访问请求
2.浏览器使用开发者工具看到有错误：
<img width="1408" alt="截屏2024-05-23 下午8 46 11" src="https://github.com/MartialBE/one-api/assets/120313253/386dab50-b2f3-4f16-b89c-50a6bb80089f">

附近为浏览器开发者日志
[one-api-0zsr.onrender.com-1716468461040.log](https://github.com/MartialBE/one-api/files/15417056/one-api-0zsr.onrender.com-1716468461040.log)

大佬看看这个是render平台的啥问题
部署的地址：https://one-api-0zsr.onrender.com

**Comment by MartialBE** [comment]
前端编译有问题。 前端页面是单页面，你切换菜单也不会有前端url的后台日志信息。
render我没有使用过。不太清楚他的流程
