### ISSUE TITLE
使用outlook邮箱发信报错 dial failed: server does not support SMTP AUTH type: PLAIN

### ISSUE THREAD

**Issue by coulsontl** [MartialBE/one-api#212]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
系统设置里配置了使用outlook邮箱发信，但是在发送邮件验证码的时候报错
<img width="1422" alt="image" src="https://github.com/MartialBE/one-api/assets/149155411/5988c800-81ad-4db5-a048-1d4a939137fe">

<img width="1236" alt="image" src="https://github.com/MartialBE/one-api/assets/149155411/a7ade5cf-6c50-4cc0-aa35-c4f975e00588">

outlook邮箱的配置说明
https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-for-outlook-com-d088b986-291d-42b8-9564-9c414e2aa040
<img width="489" alt="image" src="https://github.com/MartialBE/one-api/assets/149155411/219decbc-b689-403e-becc-2b3c5a9928b1">

在原作者的库里也看到了类似的问题，不确定有没有帮助 https://github.com/songquanpeng/one-api/issues/108#issuecomment-1653484546

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by MartialBE** [comment]
等待 dev编译完成后，拉取dev镜像尝试
docker pull ghcr.io/martialbe/one-api:dev

**Comment by coulsontl** [comment]
> 等待 dev编译完成后，拉取dev镜像尝试 docker pull ghcr.io/martialbe/one-api:dev

试了，可以正常发信，赞👍🏻
