### ISSUE TITLE
国产模型名称和价格

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-api#213]
## 混元

https://cloud.tencent.com/document/product/1729/97731

## 讯飞

https://www.xfyun.cn/doc/spark/Web.html#_1-%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E

## 智谱

https://open.bigmodel.cn/pricing

**这3个的价格好像有所变动**

> 吐槽一下, 这些国产模型的名称怎么变来变去的...

**Comment by MartialBE** [comment]
智谱已经更了。 去后台更新模型价格那里更新。
程序里面内置的价格 不想改它了，以后只更新 GitHub JSON 内的价格。
其他晚点再更吧，你也可以给 这个项目的 `prices` 分支 提PR，

ps:
百度还是那个最恶心的，模型名称和请求名称完全不一致。要不是看他免费了，我都懒得去映射他的模型名称了。

**Comment by woodchen-ink** [comment]
哈哈哈哈，好的

Best regards,

> ***@***.***>
> 时间： 2024年5月24日 (周五) 14:36
> 主题： Re: [MartialBE/one-api] 国产模型名称和价格 (Issue #213)
> ***@***.***>
> 抄送："wood ***@***.***>, ***@***.***>
> 智谱已经更了。 去后台更新模型价格那里更新。
> 
程序里面内置的价格 不想改它了，以后只更新 GitHub JSON 内的价格。
> 
其他晚点再更吧，你也可以给 这个项目的 
> prices
>  分支 提PR，
> ps:
> 
百度还是那个最恶心的，模型名称和请求名称完全不一致。要不是看他免费了，我都懒得去映射他的模型名称了。

**Comment by MartialBE** [comment]
已更新，腾讯的需要升级程序后 才能使用

**Comment by woodchen-ink** [comment]
> 已更新，腾讯的需要升级程序后 才能使用

好的，谢谢
