### ISSUE TITLE
希望聊天链接增加自定义排序功能

### ISSUE THREAD

**Issue by ZeroDeng01** [MartialBE/one-api#214]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
![image](https://github.com/MartialBE/one-api/assets/19732560/42c88e11-2c32-4329-82a1-c12a6043ce34)
希望聊天连接能增加自定义排序功能，比如增加一个字段为序号，用户可以修改，后续在使用聊天链接列表或者集合的地方可以按循序输出。
**应用场景**
比如令牌模块点击聊天按钮，里面按钮下拉顺序不可调整，只能删除重新添加才可以调整顺序。playground同样。

**Comment by MartialBE** [comment]
后续优化
