### ISSUE TITLE
希望增加description自定义功能

### ISSUE THREAD

**Issue by ZeroDeng01** [MartialBE/one-api#215]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
希望增加description自定义功能，这样有利于网站说明和关键字修改。
**应用场景**
前端description修改调整

**Comment by MartialBE** [comment]
非主要功能 优先级会低。
如果自己建站，还是自己fork代码更改比较好。

**Comment by woodchen-ink** [comment]
![image](https://github.com/MartialBE/one-api/assets/95951386/d940c9fa-36c7-40e4-b871-0bc33f5cd016)
这里自己加就好了，动态加还不方便
