### ISSUE TITLE
请问用1panel如何搭建？

### ISSUE THREAD

**Issue by GD2021** [MartialBE/one-api#216]

**Comment by woodchen-ink** [comment]
正常docker运行就行

**Comment by MartialBE** [comment]
emmmm, 我不是百科，很多的网站/工具/面板 部署流程我没用过，我也不知道啊 -。-
关于程序的部署，应该看看[wiki](https://github.com/MartialBE/one-api/wiki/Deployment) 里面。
它应该和你使用1panel部署其他应用差不多才对
