### ISSUE TITLE
qwen-max-vl 请求报错

### ISSUE THREAD

**Issue by bahuzh** [MartialBE/one-api#217]
通过open-webui调用qwen-max-vl 模型时报错，gpt-4o，glm-4v正常

**open-webui日志如下**
 INFO:     "POST /openai/api/chat/completions HTTP/1.1" 200 OK

 INFO:     "POST /api/v1/chats/4ea8d121-9f9a-4916-89b8-1498212fd72f HTTP/1.1" 200 OK

 INFO:      "GET /api/v1/chats/ HTTP/1.1" 200 OK

 INFO:      "POST /openai/api/chat/completions HTTP/1.1" 200 OK

<img width="574" alt="image" src="https://github.com/MartialBE/one-api/assets/120018648/d5845a95-82cb-4335-a71a-72b8a7513dc7">

 **one-api日志如下**
 [ERR] 2024/05/24 - 15:56:15 | 20240524155610509047721dEsdT0YB | relay error happen, status code is 500, won't retry in this case 

 [ERR] 2024/05/24 - 15:56:15 | 20240524155610509047721dEsdT0YB | relay error (channel #2(ali)): {"error":{"code":"InternalError","message":"call csiCheck no success","param":"c7527442-24d6-9762-86d9-dd830e2ff341","type":"InternalError"}} 
 

------
 
 另外，我通过终端curl使用url是正常的
 
 curl --location 'https://x.x.x.x/v1/chat/completions' \
  --header 'Authorization: Bearer xxxxx' \
  --header 'Content-Type: application/json' \
  --data '{
    "model": "qwen-vl-max",
    "messages": [
      {
        "role": "user",
        "content": [
          {
            "type": "image_url",
            "image_url": {
              "url": "https://platform.lingyiwanwu.com/assets/sample-table.jpg"
            }
          },
          {
            "type": "text",
            "text": "请详细描述一下这张图片。"
          }
        ]
      }
    ],
    "stream": false,
    "max_tokens": 1024
  }'

**Comment by MartialBE** [comment]
这是因为 它只支持 url的图片， `open-webui`是将图片base64，这个暂时没办法解决

**Comment by GrayXu** [comment]
@MartialBE  想问下有没有计划通过imgur, sm.ms 或 github来作为免费的图床空间，来实现qwen-vl支持？或者在oneapi里做这个图片的缓存？谢谢

**Comment by MartialBE** [comment]
现在就有， 只不过用于 图片生成 ，一些供应商不会传入URL，返回的是 图片数据， 你配置了图床，返回时，会上传到图床，返回图片链接。

聊天中不现实，因为你每请求一次，就上传一次图片，连续聊天中图片可能会有多张。 导致 速度慢，而且他们也有速率限制。

我也不会把图片上传保存数据库，因为他很少会被复用到。没有意义
