### ISSUE TITLE
Support together.xyz API

### ISSUE THREAD

**Issue by search-codes-now-2016** [MartialBE/one-api#218]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
添加together的API，https://www.together.ai/
**应用场景**
他们有很多开源大模型的API可以使用

**Comment by woodchen-ink** [comment]
我感觉这个好像自定义网址和模型名称就能用，跟openai的方式一样一样的
兄弟可以试试
![image](https://github.com/MartialBE/one-api/assets/95951386/aa98bba8-ff8e-4ff4-9626-46fcb0eff490)
![image](https://github.com/MartialBE/one-api/assets/95951386/8126b89d-a0e2-43f6-8a0d-b7d5f9719340)

**Comment by aiastia** [comment]
> 我感觉这个好像自定义网址和模型名称就能用，跟openai的方式一样一样的 兄弟可以试试 ![image](https://github.com/MartialBE/one-api/assets/95951386/aa98bba8-ff8e-4ff4-9626-46fcb0eff490) ![image](https://github.com/MartialBE/one-api/assets/95951386/8126b89d-a0e2-43f6-8a0d-b7d5f9719340)
但是获取模型的按钮无法使用

**Comment by woodchen-ink** [comment]
> > 我感觉这个好像自定义网址和模型名称就能用，跟openai的方式一样一样的 兄弟可以试试 ![image](https://github.com/MartialBE/one-api/assets/95951386/aa98bba8-ff8e-4ff4-9626-46fcb0eff490) ![image](https://private-user-images.githubusercontent.com/95951386/333567962-8126b89d-a0e2-43f6-8a0d-b7d5f9719340.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA5ODYxODEsIm5iZiI6MTc0MDk4NTg4MSwicGF0aCI6Ii85NTk1MTM4Ni8zMzM1Njc5NjItODEyNmI4OWQtYTBlMi00M2Y2LThhMGQtYjdkNWY5NzE5MzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzAzVDA3MTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZWU2NTZkZWE3N2VlZmQ0ZmUwM2EyZmQwMDI0YjJlMDhkMzQ4NjM4ZWQ2MmU3OTgwNTQzOGQ4MTI1ODVkMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5ZlUTL5CJ6_3GxFpdKJ1WLRtUjptMaVADjmDHozF6eQ)
> > 但是获取模型的按钮无法使用

你看这个页面有获取可用模型的接口吗

**Comment by aiastia** [comment]
> > > 我感觉这个好像自定义网址和模型名称就能用，跟openai的方式一样一样的 兄弟可以试试 ![image](https://github.com/MartialBE/one-api/assets/95951386/aa98bba8-ff8e-4ff4-9626-46fcb0eff490) ![image](https://private-user-images.githubusercontent.com/95951386/333567962-8126b89d-a0e2-43f6-8a0d-b7d5f9719340.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDA5ODYxODEsIm5iZiI6MTc0MDk4NTg4MSwicGF0aCI6Ii85NTk1MTM4Ni8zMzM1Njc5NjItODEyNmI4OWQtYTBlMi00M2Y2LThhMGQtYjdkNWY5NzE5MzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzAzVDA3MTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZWU2NTZkZWE3N2VlZmQ0ZmUwM2EyZmQwMDI0YjJlMDhkMzQ4NjM4ZWQ2MmU3OTgwNTQzOGQ4MTI1ODVkMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5ZlUTL5CJ6_3GxFpdKJ1WLRtUjptMaVADjmDHozF6eQ)
> > > 但是获取模型的按钮无法使用
> 
> 你看这个页面有获取可用模型的接口吗

我看文档是有的 https://docs.together.ai/reference/models-1

![Image](https://github.com/user-attachments/assets/1d77dd19-b530-4193-a21a-b7cb07c78bcc)
