### ISSUE TITLE
coze api 不支持 input/output token 统计

### ISSUE THREAD

**Issue by k8scat** [MartialBE/one-api#221]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

coze api 不支持 input/output token 统计

**复现步骤**

新建 coze 渠道，使用 coze 模型即可复现

**预期结果**

实现调用 token 计算

<img width="130" alt="image" src="https://github.com/MartialBE/one-api/assets/55872984/aed585b6-b42e-4d81-bd4d-ccd79164e0fc">

**相关截图**

<img width="550" alt="image" src="https://github.com/MartialBE/one-api/assets/55872984/2a8c30dc-0b79-437e-a448-a6b9ee7c4f3e">

**Comment by MartialBE** [comment]
已更新。
