### ISSUE TITLE
建议增加自定义请求路径（API前缀）功能

### ISSUE THREAD

**Issue by ssfun** [MartialBE/one-api#222]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [✅] 我已确认目前没有类似 issue
+ [✅ ] 我已确认我已升级到最新版本
+ [✅ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [✅ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [✅ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
希望能增加环境变量 API_PREFIX ，作为API 前缀，设置后需请求 /your_prefix/v1/chat/completions

**应用场景**
huggingface  space 部署 one-api ，huggingface限制访问 /v1/chat/completions，会报 {"error":{"proxy_note":"Server unavailable, error code: 349453"}}
添加自定义API前缀，可以实现正常请求，在其它项目上已经实验过，可行。

=============================
我自己尝试修改 router/relay-router.go 中的 relayV1Router := router.Group("/v1") 为 relayV1Router := router.Group("/api/v1") 
但是请求会报错 {"error":{"message":"Not Found","type":"one_api_error"}}。不知道该怎么修改，特来请教。感谢！

**Comment by MartialBE** [comment]
其实不用更改代码的， 你在 `Nginx` 或者 `caddy` 进行配置就好了。

以caddy为例子：
```
your-domain.com {
        handle_path /your_prefix/v1/* {
             rewrite * /v1{path}
             reverse_proxy http://127.0.0.1:3000
        }
        reverse_proxy http://127.0.0.1:3000
}

```

如果你想要改代码，那么你还需要改 这里的判断：
https://github.com/MartialBE/one-api/blob/671aa51f426f5efeb737328677b0028463a48b7a/relay/common.go#L23

**Comment by ssfun** [comment]
感谢解疑，修改common.go后，可以正常请求了
