### ISSUE TITLE
对渠道设置倍率

### ISSUE THREAD

**Issue by Raikyou** [MartialBE/one-api#224]
同时接入官方api和多个中转站后，会引起价格计算不准确。例如：下图中转站的对官方模型价格有调整。我可以对这家中转站不同倍率的模型分别创建渠道，希望可以加个渠道字段，支持对不同渠道分别设置相对官方价格的倍率
![image](https://github.com/MartialBE/one-api/assets/13917879/32dbb4d0-e197-40e3-9a3a-1ed4db5bc7f2)

**Comment by woodchen-ink** [comment]
居然有比官方价贵这么多的中转。。。

**Comment by MartialBE** [comment]
这个会让 整个渠道 更加难以管理，而且计费 十分混乱。
用户请求同样的 模型，却有 几个不同的价格计费。
暂时不会考虑这个需求

**Comment by woodchen-ink** [comment]
折中点或许可以部署两个站点，在2站点只建立这个中转的渠道，然后设置价格。然后在1站点接入2站点
核对成本时看2站点的

仅供参考
