### ISSUE TITLE
arm版可否出个骨头版？用于低内存低存储的路由器等等

### ISSUE THREAD

**Issue by kknd222** [MartialBE/one-api#226]
**功能描述**

希望能有模块化设计以及定制功能启用禁用

**应用场景**

小内存及存储资源的硬件，比如soho路由；
个人用户并非商业性质的粗放式管理配置。

**Comment by MartialBE** [comment]
只要不启用 tiktoken 编码器就好了，他占用了40M左右的内存，主程序的内存占用只有10M多。
dev已经增加了`DISABLE_TOKEN_ENCODERS`配置： 启用后，不会加载 tiktoken，可节省40M左右内存， 但是stream模式下tokens计算不准确。


你可以先自己编译一下或者拉取dev镜像，然后在`config.yaml`将`disable_token_encoders`设为`true`
