### ISSUE TITLE
点击 Playground 会自动创建令牌，会被使用，怎么解决这个问题

### ISSUE THREAD

**Issue by candies404** [MartialBE/one-api#230]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
点击 Playground 会自动创建令牌,
![image](https://github.com/MartialBE/one-api/assets/154443166/7e8411a2-67a0-43c1-a29c-392f870e5749)

![image](https://github.com/MartialBE/one-api/assets/154443166/28e19667-8dd5-4a7c-a84f-22f54c7bcf30)

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by MartialBE** [comment]
这是feature。
如果你不想自动填充。请在设置中 聊天链接设置 重新配置链接。但系统令牌还是会创建。
