### ISSUE TITLE
更新0.90 后，chatgpt-nextchat  经常报  unknown_parameter  stream_options

### ISSUE THREAD

**Issue by 80imike** [MartialBE/one-api#231]
<img width="949" alt="image" src="https://github.com/MartialBE/one-api/assets/1665201/eb4f8599-4326-4fc9-ad07-d5db73441ba6">

这个是因为 chatgpt-nextchat 还不支持 stream_options 吗？

**Comment by MartialBE** [comment]
请看发版说明。

**Comment by 80imike** [comment]
> 请看发版说明。
已经看到了，我在改 自定义渠道 试下
