### ISSUE TITLE
dall-e-3 調用錯誤

### ISSUE THREAD

**Issue by bentwnghk** [MartialBE/one-api#240]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
dall-e-2 可以調用，但 dall-e-3 調用錯誤，是什麼原因？
**复现步骤**

**预期结果**

**相关截图**
![螢幕擷取畫面 2024-05-29 072656](https://github.com/MartialBE/one-api/assets/101241940/727877d7-34a4-4366-89c4-8982efc8e4a8)

**Comment by bentwnghk** [comment]
在 令牌-->编辑令牌-->勾選"无限额度"後可調用dall-e-3了，設計原意是這樣嗎？

有辦法在設置令牌额度後仍然可調用dall-e-3嗎？

**Comment by MartialBE** [comment]
是否 是你的令牌 额度太低了？ 调高你的令牌额度呢？

**Comment by bentwnghk** [comment]
> 是否 是你的令牌 额度太低了？ 调高你的令牌额度呢？

令牌额度設為10000000 (=$20)的時候，無法調用dall-e-3
把令牌额度設為15000000 (=$30)，可調用dall-e-3了 !

**Comment by MartialBE** [comment]
你是否把`请求预扣费额度`设置的太高了？ 或者 你有改变`dall-e-3`的价格吗

**Comment by bentwnghk** [comment]
> 你是否把`请求预扣费额度`设置的太高了？ 或者 你有改变`dall-e-3`的价格吗

500000
是否太高？

**Comment by ZeroDeng01** [comment]
> > 你是否把`请求预扣费额度`设置的太高了？ 或者 你有改变`dall-e-3`的价格吗
> 
> 500000 是否太高？

`请求预扣费额度`设置的太高了，一般设置在`单次会话`token消耗数量范围内就行。比如设置`1000`。

**Comment by bentwnghk** [comment]
> > > 你是否把`请求预扣费额度`设置的太高了？ 或者 你有改变`dall-e-3`的价格吗
> > 
> > 
> > 500000 是否太高？
> 
> `请求预扣费额度`设置的太高了，一般设置在`单次会话`token消耗数量范围内就行。比如设置`1000`。

你說對了，我把調低到1000，把令牌额度設為10000000 (=$20)，可調用dall-e-3了 !　謝謝你！

**Comment by MartialBE** [comment]
预扣费 = (系统计算的输入token + 请求预扣费额度) x 模型输入倍率
系统默认一张图片的输入token为 1000，其他全靠 模型输入倍率 来变动 不同模型的价格。
而 `dall-e-3` 的倍率为 20.
则就导致了 (1000 + 500000 ) * 20 = 10020000 , 需要账户拥有 20.04的余额才能请求。


所以不要把 请求预扣费额度 设置很高，会以倍数增长。

**Comment by MartialBE** [comment]
PS： 或许 把  请求预扣费额度 往后，
改成 预扣费 = 系统计算的输入token x 模型输入倍率 + 请求预扣费额度 
这样会比较合理一些吗？

可以讨论一下。

**Comment by bentwnghk** [comment]
> PS： 或许 把 请求预扣费额度 往后， 改成 预扣费 = 系统计算的输入token x 模型输入倍率 + 请求预扣费额度 这样会比较合理一些吗？
> 
> 可以讨论一下。

好像後者比較合理一點，账户拥有 1.04的余额便能请求dall-e-3。

**Comment by ZeroDeng01** [comment]
> PS： 或许 把 请求预扣费额度 往后， 改成 预扣费 = 系统计算的输入token x 模型输入倍率 + 请求预扣费额度 这样会比较合理一些吗？
> 
> 可以讨论一下。

这样应该会合理一点，正常请求预扣费便是一个授信额的常量，不需要参与倍率计算。如果真要计算那也不是模型倍率，只需要参与分组倍率就行，因为模型倍率相对所有人都一样，而分组倍率不同。即：`预扣费 = 系统计算的输入token x 模型输入倍率 + 请求预扣费额度x分组倍率`。
这样不会导致冻结费用太多也不至于预扣太少导致用户超支太多。

**Comment by MartialBE** [comment]
可以的。 晚点改一下

**Comment by MartialBE** [comment]
分组倍率 还有必要 乘么。 我感觉直接加就好了。便于理解

**Comment by ZeroDeng01** [comment]
> 分组倍率 还有必要 乘么。 我感觉直接加就好了。便于理解

这样也是ok的，预扣主要是授信作用，而且可调节
