### ISSUE TITLE
升级v0.9.1 卡在这个界面时间很久，正常吗？

### ISSUE THREAD

**Issue by igeekbb** [MartialBE/one-api#245]
**问题描述**
<img width="767" alt="image" src="https://github.com/MartialBE/one-api/assets/154116268/41f12fef-1910-4049-98e7-cbec3017e5ae">

**复现步骤**

**预期结果**

**Comment by MartialBE** [comment]
这是在下载 编码器中。 网络是否正常？

**Comment by igeekbb** [comment]
> 这是在下载 编码器中。 网络是否正常？

正常，已经启动，只是在这个界面的时间有点长，后面正常启动了

**Comment by ZeroDeng01** [comment]
> > 这是在下载 编码器中。 网络是否正常？
> 
> 正常，已经启动，只是在这个界面的时间有点长，后面正常启动了

建议把编码器持久化，这样不用每次重启或者更新服务都需要下载码表。使用方式参考[文档](https://github.com/MartialBE/one-api/wiki/Environment#%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)环境变量设置部分的`TIKTOKEN_CACHE_DIR`和`DATA_GYM_CACHE_DIR`
