### ISSUE TITLE
部署文档可以写清楚 -p xxxx:3000,其中镜像端口3000不可以更改,宿主机端口可以随便改

### ISSUE THREAD

**Issue by Jazzylol** [MartialBE/one-api#248]
改了docker 端口，前端无法访问

**Comment by ZeroDeng01** [comment]
> 改了docker 端口，前端无法访问

这个正常来说按照手册复制docker指令或使用提供的docker compose部署不会出问题的。项目私有化需要有一定的基础技术储备。`-p 宿主端口:服务端口`这个基本是docker基础，不建议加入到部署文档里面，不然会导致文档比较臃肿。

**Comment by Jazzylol** [comment]
1. 我使用 https://github.com/MartialBE/one-api/wiki/Deployment 文档里的docker-compose方式部署，我把docker-compose的env变量全删除了。
2. 文档中说config文件需要放置到 ./data/one-api文件夹下，我按照文档部署发现一直无法正常读取配置，所以我当时误解了port是不可以修改的。
3. 看了下源码 workdir /data  所以 config.yaml应该是 放置到./data 下，不是./data/one-api ，我自己测试了下也正常读取到配置了。
4. 所以应该是部署文档 docker-compose部分描述错了，你可以测试下。

**Comment by nb5p** [comment]
可以使用命令行参数修改监听端口号。

--port <port_number>: 指定服务器监听的端口号，默认为 3000。

**Comment by zodiacg** [comment]
> 1. 我使用 https://github.com/MartialBE/one-api/wiki/Deployment 文档里的docker-compose方式部署，我把docker-compose的env变量全删除了。
> 2. 文档中说config文件需要放置到 ./data/one-api文件夹下，我按照文档部署发现一直无法正常读取配置，所以我当时误解了port是不可以修改的。
> 3. 看了下源码 workdir /data  所以 config.yaml应该是 放置到./data 下，不是./data/one-api ，我自己测试了下也正常读取到配置了。
> 4. 所以应该是部署文档 docker-compose部分描述错了，你可以测试下。

建议检查一下自己的docker-compose.yml。官方docker-compose把*宿主机*的`./data/one-api`映射到了*容器内*的`/data`，所以config.yaml放置在`./data/one-api`下会出现在容器里的`/data`里，这与`workdir /data`是一致的，没有问题。

建议学习一下docker相关基础知识。
