### ISSUE TITLE
请问默认账号是多少?

### ISSUE THREAD

**Issue by Timoshao** [MartialBE/one-api#25]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
部署命令如下：
docker run --name one-api -d --restart always -p 3000:3000 -e TZ=Asia/Shanghai -v /home/ubuntu/data/one-api:/data ghcr.io/martialbe/one-api:dev

**复现步骤**
使用root账号 123456密码无法登录
**预期结果**

**相关截图**
![image](https://github.com/MartialBE/one-api/assets/108260847/67cdfe11-e90e-4d06-aa89-657e2afd54d9)

如果没有的话，请删除此节。

**Comment by MartialBE** [comment]
我这边检测是正常的。
请检测
1. 本机是否存在` /home/ubuntu/data/one-api`目录， 没有请创建，或者更改已有目录
2. ` /home/ubuntu/data/one-api`存在的话，是否之前有测试过？更改过帐号密码？ 可以尝试把这个目录下的 `one-api.db`删除后在重启启动docker

**Comment by Timoshao** [comment]
> 我这边检测是正常的。 请检测
> 
> 1. 本机是否存在` /home/ubuntu/data/one-api`目录， 没有请创建，或者更改已有目录
> 2. ` /home/ubuntu/data/one-api`存在的话，是否之前有测试过？更改过帐号密码？ 可以尝试把这个目录下的 `one-api.db`删除后在重启启动docker

谢谢解决了。应该是之前部署过one-api导致的
