### ISSUE TITLE
自定义渠道无法使用

### ISSUE THREAD

**Issue by shengshiyuanhua** [MartialBE/one-api#26]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
"错误":{
"message": "检测到Panic，错误:运行时错误:无效的内存地址或空指针解引用。"请在这里提交问题:https://github.com/songquanpeng/one-api”，
“类型”:“one_api_panic”
｝
｝
**复现步骤**
在进行对话时报错
**预期结果**

**Comment by MartialBE** [comment]
麻烦告知一下是使用什么渠道模型。
可以复现吗

**Comment by shengshiyuanhua** [comment]
使用的是自定义渠道，自定义渠道所使用的是one-api的，直接使用one-api的没问题，在咱们这个中做了自定义渠道后在测试余额时总会让重新登录，
![测试后会提示重新登录](https://github.com/MartialBE/one-api/assets/36113190/854a7a13-289b-465d-858e-732d32361299)
![通过chatweb测试报错，其他中转均没问题](https://github.com/MartialBE/one-api/assets/36113190/985d9cab-bcbf-4437-95f4-5a3eb2f12d3a)
通过chatweb测试报错，其他中转通过chatweb测试均没问题

**Comment by MartialBE** [comment]
已修复， 请重新拉取 dev镜像。
