### ISSUE TITLE
支持其他模型function调用

### ISSUE THREAD

**Issue by MartialBE** [MartialBE/one-api#28]
许多大型模型都支持函数调用，但目前存在一些问题：
- Stream调用的输出方式与第三方软件不兼容，导致无法读取函数参数，从而导致调用失败。
- 国产大型模型具有固定的 `role`，以及固定的`role`顺序和数量限制，这可能导致即使函数调用成功，由于`msg`顺序的问题也可能导致失败。

因此，我们需要对 stream 调用进行兼容处理，以符合OpenAI的规范。同时，我们也需要对传入的`msg`进行检查，以确保它们符合对应模型的`msg`限制。

**Comment by paulcx** [comment]
目前OpenAI的tools支持吗？
