### ISSUE TITLE
希望渠道中加入openrouter支持

### ISSUE THREAD

**Issue by xinlonzh** [MartialBE/one-api#282]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
虽然openrouter采用openai兼容api，但使用自定义渠道添加，需要配置nginx代理，请求中添加HTTP-Referer和X-Title，原项目已解决该问题，请求参考原项目加入此渠道，谢谢！
**应用场景**
拓展渠道冗余 分担负载压力 保证服务
**相关链接**
官网地址: https://openrouter.ai/
接口文档: https://openrouter.ai/docs

**Comment by MartialBE** [comment]
可以直接使用 指定渠道 使用
