### ISSUE TITLE
部分渠道点击编辑后，大部分选项都是灰色，无法编辑更新

### ISSUE THREAD

**Issue by jinxishe** [MartialBE/one-api#285]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
![f153caaf-0426-4e2d-8629-fb2493801494](https://github.com/MartialBE/one-api/assets/25061293/9bb0eed8-7965-4ee1-801e-6cd937e9326c)

如图，部分渠道（不是所有渠道，有些可以更新）点击编辑后，画面上多数选项都是灰色，无法更新，也无法修改或添加新的模型名称。没有找到具体的规律，不知道原因是什么？

**Comment by jinxishe** [comment]
似乎是加了标签的渠道就无法编辑更新了？删了标签就可以更新。这个功能逻辑是这样的吗？为什么呢？

**Comment by MartialBE** [comment]
因为加了标签应该在渠道标签列表进行编辑。
保证所有同一个标签下的渠道设置是一致的。

**Comment by jinxishe** [comment]
> 因为加了标签应该在渠道标签列表进行编辑。 保证所有同一个标签下的渠道设置是一致的。

建议在渠道页面上对标签的使用逻辑做一些说明。我原本以为标签是可以自由使用的，比如我对某些渠道打了“有余额”的标签，某些则打了“无余额”，但当我想对其中某个渠道增加或修改模型时，目前的逻辑似乎不太适合。所以建议做一些逻辑和用法的说明。
