### ISSUE TITLE
打了统一标签的渠道，API地址会被修改为首个渠道的URL

### ISSUE THREAD

**Issue by LoveU3th** [MartialBE/one-api#288]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
打了统一标签的渠道，API地址会被修改为首个渠道的URL
昨天发现过一次，一个一个手动修改回来，今天又发现变成了统一的URL，导致不能访问
**复现步骤**
可能是操作编辑标签并提交后
**预期结果**

**相关截图**
![image](https://github.com/MartialBE/one-api/assets/50294305/cd578e08-e485-4e7a-8521-5c5ca8a93dac)

**Comment by MartialBE** [comment]
已修复
