### ISSUE TITLE
求完善一个渠道自动禁用的功能

### ISSUE THREAD

**Issue by jqlts1** [MartialBE/one-api#290]
目前的渠道禁用的逻辑是这样的
<img width="552" alt="image" src="https://github.com/MartialBE/one-api/assets/17434370/d5730037-11ae-48c0-96e2-af201c63feca">

渠道如果被禁用以后,还会再被使用? 我觉得正确的逻辑应该是:
1. 渠道连续失败累积到一定次数以后禁用
2. 如果第一次失败,第二次成功,这种就不要禁用

因为现在大部分的厂家,都有控频设置,如果频率过高,也会失败,或是因为网络问题也有可能会失败,但是你再过一会就成功了,这种就不应该被禁用掉

**Comment by MartialBE** [comment]
这里的失败 不是请求不成功就禁用
而是会判断错误类型的。 速率达到上限不会被禁用。
详情请看controller/common.go

**Comment by jqlts1** [comment]
> 这里的失败 不是请求不成功就禁用
> 而是会判断错误类型的。 速率达到上限不会被禁用。
> 详情请看controller/common.go

是全渠道都会自动判断类型吗？

**Comment by MartialBE** [comment]
应该没有覆盖到全渠道方面。根据错误信息关键字来去匹配。 这里逻辑是原one api的逻辑
