### ISSUE TITLE
是不是只支持baseurl为https://的api站点

### ISSUE THREAD

**Issue by bohesocool** [MartialBE/one-api#291]
我调用了一个人的newapi站点测试，结果报错403，我在想是不是因为它是https://wvw的问题，newapi调用的话是能够成功调用的。

**Comment by MartialBE** [comment]
报错信息呢？
能返回说明请求成功了
请检查你的key是否正确

**Comment by bohesocool** [comment]
![image](https://github.com/MartialBE/one-api/assets/129200122/ff05ca9e-b2eb-4886-bd29-f8fe8b59d4f6)
这个是报错信息，key是正确的，我在我的newapi站上面是能够成功调用的。

**Comment by MartialBE** [comment]
你的渠道类型是 自定义吗？ 改成自定义试试？

**Comment by bohesocool** [comment]
不是自定义哦，是别的的newapi，所以我就感觉有点奇怪

**Comment by MartialBE** [comment]
我的意思是 你把渠道类型 改成 自定义渠道 试试

**Comment by bohesocool** [comment]
我改成了自定义，还是同样的报错

**Comment by MartialBE** [comment]
那很奇怪🤔
一般都抛出403错误了。你的url应该是没问题的。鉴权有问题

**Comment by bohesocool** [comment]
我也不知道什么情况。。但是那个new站要绑定论坛，也无法发给你看

**Comment by MartialBE** [comment]
绑定论坛账户是账户， API调用是 key呀

**Comment by bohesocool** [comment]
GitHub如何私信呢

**Comment by MartialBE** [comment]
可以发送我邮箱[buer@xiao5.info](mailto:buer@xiao5.info)

**Comment by bohesocool** [comment]
发给你了

**Comment by MartialBE** [comment]
程序没有问题。
请联系你的商家， 放行规则添加 User-Agent: Go-http-client/1.1

**Comment by bohesocool** [comment]
好的好的
