### ISSUE TITLE
无法正常调用glm这几个模型,官方渠道

### ISSUE THREAD

**Issue by Passerby1011** [MartialBE/one-api#292]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
无法正常调用glm-4-flash,glm-4-airx,glm-4-airx这几个模型
**复现步骤**
正常填入调用
**预期结果**

**相关截图**
![image](https://github.com/MartialBE/one-api/assets/63802758/bcc8029b-2ec6-4930-8d5f-8f72ae3d1cb6)

**Comment by MartialBE** [comment]
均调用正常

<img width="1068" alt="iShot_2024-07-07_00 44 01" src="https://github.com/MartialBE/one-api/assets/42402987/d7c519ff-7b0e-4c4b-be27-b007aefde12d">

**Comment by MartialBE** [comment]
模型测试也是通不过吗？ 程序是最新版本的吗？

**Comment by Passerby1011** [comment]
现在的状况很奇怪
我使用的客户端是librechat，他可正常调用该项目的所有其他模型，唯一无法调用的就是智谱官方渠道的模型，按道理来说oneapi出来的都是openai的格式，调用方式都一样，其他都行不知道为啥glm不行

**Comment by Passerby1011** [comment]
分客户端，有的就可以正常调用，有的客户端就不行

**Comment by Passerby1011** [comment]
如果你想测试最简单的测试无法调用的客户端是这个浏览器插件
https://github.com/josStorer/chatGPTBox

**Comment by Passerby1011** [comment]
> 模型测试也是通不过吗？ 程序是最新版本的吗？
之前的版本是可以正常调用的不知道是智谱更新了还是oneapi的更新导致了有些客户端无法使用
这是之前的调用日志
![image](https://github.com/MartialBE/one-api/assets/63802758/05fcc01f-7012-41e2-9af8-d5bf95c8898c)

**Comment by MartialBE** [comment]
已修复
