### ISSUE TITLE
Vertex AI 调用api是否多了一个“-”？

### ISSUE THREAD

**Issue by Silentely** [MartialBE/one-api#298]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
调用Vertex AI，测试提示请求上游地址错误，查看日志，对比官方提供的API地址发现多了一个“-”符号
**复现步骤**
配置好KEY，点击测试模型
**预期结果**
测试通过
**相关截图**

![c591da5978658f13b5a0014aff314ef2.jpeg](https://ice.frostsky.com/2024/07/14/c591da5978658f13b5a0014aff314ef2.jpeg)
![442aa640cdec6b4327a0ece40af5deb8.jpeg](https://ice.frostsky.com/2024/07/14/442aa640cdec6b4327a0ece40af5deb8.jpeg)
![0cec1cf30213f8498ab78156c12cb297.jpeg](https://ice.frostsky.com/2024/07/14/0cec1cf30213f8498ab78156c12cb297.jpeg)

**Comment by MartialBE** [comment]
<img width="356" alt="image" src="https://github.com/user-attachments/assets/f1c9848f-6ea0-451b-9d4c-20b09bb0ec6f">

**Comment by 3377** [comment]
这里其他参数填什么，文档里没有写啊！

**Comment by 3377** [comment]
对应的文档地址在哪呀，好神奇，你们是怎么找到的。

**Comment by Silentely** [comment]
> 对应的文档地址在哪呀，好神奇，你们是怎么找到的。

没有对应的文档，截图里不是有写吗？你看细点

**Comment by 3377** [comment]
![image](https://github.com/user-attachments/assets/1bfb92bd-4cc6-48c8-ab13-a8d8f1eef107)
我填了一下，测速报错如下

**Comment by Silentely** [comment]
> 请教一下，这个Region是填对应的哪个啊，只要有配额的那个就行吗？还是

你项目对应的地区，例如
us-east5|premium-xxxx-xxx

**Comment by 3377** [comment]
我特意去设置了一下区域，给对应的输入了，提示
![image](https://github.com/user-attachments/assets/2d89e9da-fcad-4f5a-9d5e-657c374cf1c9)
方便帮忙排错下吗？日志这么现实
![image](https://github.com/user-attachments/assets/67b5c540-5f1c-44b4-adb9-db7f356c9960)

**Comment by 3377** [comment]
![image](https://github.com/user-attachments/assets/1e797049-683e-455b-880e-88a4dd227ffe)
这里额度也没问题

**Comment by Silentely** [comment]
> 我特意去设置了一下区域，给对应的输入了，提示 ![image](https://private-user-images.githubusercontent.com/15319161/359123064-2d89e9da-fcad-4f5a-9d5e-657c374cf1c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNzU1NTUsIm5iZiI6MTcyNDA3NTI1NSwicGF0aCI6Ii8xNTMxOTE2MS8zNTkxMjMwNjQtMmQ4OWU5ZGEtZmNhZC00ZjVhLTlkNWUtNjU3YzM3NGNmMWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDEzNDczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NzIyOTkyNWU2NDk4ODgyYWUwMzhhZmZkZDg0OTNkZmUzMGNhZjY1OTk4ODA2ZGE3OWIyNGE4NmY1ODY4MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kiM-hggIxUqhPoa5ZNFo1Jn1mlysaBzUcOLF2N0FftA) 方便帮忙排错下吗？日志这么现实 ![image](https://private-user-images.githubusercontent.com/15319161/359123394-67b5c540-5f1c-44b4-adb9-db7f356c9960.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNzU1NTUsIm5iZiI6MTcyNDA3NTI1NSwicGF0aCI6Ii8xNTMxOTE2MS8zNTkxMjMzOTQtNjdiNWM1NDAtNWYxYy00NGI0LWFkYjktZGI3ZjM1NmM5OTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDEzNDczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ODBiYjA1MjkwNDk4ZjNiOTI4OTFlN2Y5MGU1NGJjYjNlMTc3NWZmMWMwN2UxNWJlYWNkNDhmN2UwM2FlNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4kZYXlYbvwjSwNB3TVINxz5gSEuIKwe95Pt7WwycylI)

估计是你没有去开通对应的模型，文档里没有写明要自己去开对应的模型
https://cloud.google.com/vertex-ai/generative-ai/docs/partner-models/use-claude?hl=zh-cn#claude-3-5-sonnet
![279381ed43e4aade970bec2633a54300.jpeg](https://ice.frostsky.com/2024/08/19/279381ed43e4aade970bec2633a54300.jpeg)

**Comment by 3377** [comment]
![image](https://github.com/user-attachments/assets/376ce28f-5767-4eb7-8076-d9c1f046f8b9)
已成功，大佬厉害，这个文档真的是一言难尽。gcp的没法用3.5的吗

**Comment by Silentely** [comment]
> ![image](https://private-user-images.githubusercontent.com/15319161/359128186-376ce28f-5767-4eb7-8076-d9c1f046f8b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNzY5MDcsIm5iZiI6MTcyNDA3NjYwNywicGF0aCI6Ii8xNTMxOTE2MS8zNTkxMjgxODYtMzc2Y2UyOGYtNTc2Ny00ZWI3LTgwNzYtZDljMWYwNDZmOGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE0MTAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ODRmYjEyZGU3YTUwMDNhMzliODMwYTBlNGIwYzNhOGRlZDAxYTQyNWNkNjBjOTJmNTRjNzJkZDUzODk3NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1r1Oi53n1WQ2fqEI_aQU9LiVTQ5gTcztmglNvBu5xvw) 已成功，大佬厉害，这个文档真的是一言难尽。gcp的没法用3.5的吗

可以用，一共4个模型，每个都要手动点击开通

**Comment by 3377** [comment]
没有文档，佩服你能弄出来。这个面板能禁用模型映射的原名称吗？
![image](https://github.com/user-attachments/assets/b8761cbd-30b3-4e4b-a944-77cfcafe3631)
类似NIO的这个功能。

**Comment by Silentely** [comment]
> 没有文档，佩服你能弄出来。这个面板能禁用模型映射的原名称吗？ ![image](https://private-user-images.githubusercontent.com/15319161/359132773-b8761cbd-30b3-4e4b-a944-77cfcafe3631.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNzcyMDYsIm5iZiI6MTcyNDA3NjkwNiwicGF0aCI6Ii8xNTMxOTE2MS8zNTkxMzI3NzMtYjg3NjFjYmQtMzBiMy00ZTRiLWE5NDQtNzdjZmNhZmUzNjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE0MTUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlNzJkNzhlZDVmYjg3ODg4Y2JhZDVhNGE5OTJkNzJjYWRmM2VhZTYwOGZiYmI2ODJkMzJiNDU2OTY1Yzk0NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z4z4j5TFvUPBaMVXwcIj9P7uSBRUsIkQh14KIQs5G6g) 类似NIO的这个功能。

模型关系那一栏就是模型映射，你自己按照需求改，以下仅提供示例
{
  "claude-3-haiku": "claude-3-haiku-20240307",
  "claude-3-opus": "claude-3-opus-20240229",
  "claude-3-sonnet": "claude-3-sonnet-20240229",
  "claude-3.5-sonnet": "claude-3-5-sonnet-20240620"
}

**Comment by 3377** [comment]
这个我了解，我的意思是能否隐藏原来的。

**Comment by Silentely** [comment]
> 这个我了解，我的意思是能否隐藏原来的。

不好意思这个没明白，如果是说渠道模型，那里你可以自己选择删除或者添加，不知道你说的是不是这个，或者是我没用过你说的这个功能，只能等作者来回复你

**Comment by 3377** [comment]
比如我的API里有你写的第一个claude-3-haiku-20240307模型，我通过映射
"claude-3-haiku": "claude-3-haiku-20240307",
改为了claude-3-haiku，那此时我通过第三方调用的时候我可以隐藏掉claude-3-haiku-20240307展示在使用者获取的模型列表里。

**Comment by Silentely** [comment]
> 比如我的API里有你写的第一个claude-3-haiku-20240307模型，我通过映射 "claude-3-haiku": "claude-3-haiku-20240307", 改为了claude-3-haiku，那此时我通过第三方调用的时候我可以隐藏掉claude-3-haiku-20240307展示在使用者获取的模型列表里。

你意思是第三方通过比如api.xxx.xx/model获取的模型列表里隐藏掉这个吗？如果是这个的话我没试过，我只试过在web项目里直接增加模型，没有试过获取对应的模型列表

**Comment by 3377** [comment]
好的，了解了，再次感谢你的解答。
