### ISSUE TITLE
更新后仍然遇到问题

### ISSUE THREAD

**Issue by shengshiyuanhua** [MartialBE/one-api#30]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
接入平台是one-api的，直接访问及调用都可以。
以下是点击测试时的报错：
错误：Post "https://openapi.useropen.cloud/v1/chat/completions": malformed HTTP response "\x00\x00\x12\x04\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x80\x00\x04\x00\x01\x00\x00\x00\x05\x00\xff\xff\xff\x00\x00\x04\b\x00\x00\x00\x00\x00\x7f\xff\x00\x00\x00\x00\b\a\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01"

以下是对话时报的错误：
{
  "error": {
    "code": "http_request_failed",
    "message": "Post \"https://openapi.useropen.cloud/v1/chat/completions\": malformed HTTP response \"\\x00\\x00\\x12\\x04\\x00\\x00\\x00\\x00\\x00\\x00\\x03\\x00\\x00\\x00\\x80\\x00\\x04\\x00\\x01\\x00\\x00\\x00\\x05\\x00\\xff\\xff\\xff\\x00\\x00\\x04\\b\\x00\\x00\\x00\\x00\\x00\\x7f\\xff\\x00\\x00\\x00\\x00\\b\\a\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x01\" (request id: 20240107110956560574366zmXOkGxs)",
    "type": "one_api_error"
  }
}
**复现步骤**
使用的对话模型是3.5
使用的是自定义的one-api渠道
**预期结果**

**相关截图**
![微信截图_20240107110905](https://github.com/MartialBE/one-api/assets/36113190/0fd7762a-6778-4ef5-b6d3-57f892687fe0)
![微信截图_20240107111601](https://github.com/MartialBE/one-api/assets/36113190/738df2ca-e271-42d6-99fe-32a365ac18f5)
![微信截图_20240107111723](https://github.com/MartialBE/one-api/assets/36113190/248bce39-44d5-45da-b6d8-5a1609b9df19)

**Comment by MartialBE** [comment]
这个错误是[https://openapi.useropen.cloud](https://openapi.useropen.cloud/v1/chat/completions)响应有问题。
我这边测试 自定义 链接one api平台 可以正常使用的。
如果你方便提供该平台的`key`，我可以测试一下。
buer@xiao5.info

**Comment by shengshiyuanhua** [comment]
sk-Jad6rWpK1cZ5pEz138Fc9cC42063478d81B74b2192F117Bb
这个就是我这个平台的key，正常使用中的

**Comment by MartialBE** [comment]
我这边测试正常。是否网络问题？
**记得把 上面的key 删除了。不要被盗用了**

<img width="1092" alt="iShot_2024-01-07_17 29 13" src="https://github.com/MartialBE/one-api/assets/42402987/b923b0cc-7e09-48d3-8d87-2d727b848212">
<img width="1068" alt="iShot_2024-01-07_17 29 00" src="https://github.com/MartialBE/one-api/assets/42402987/193dfe72-6496-4690-a233-c7dff3b36652">

**Comment by shengshiyuanhua** [comment]
好，谢谢，我在研究研究，这个BUG提交可以去除了

**Comment by shengshiyuanhua** [comment]
感谢，辛苦了~
