### ISSUE TITLE
embedding 接口好像有问题

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-api#31]
![image](https://github.com/MartialBE/one-api/assets/95951386/0a0c46f4-91b1-4454-b97a-84a1d454a5f8)

``` bash

[ERR] 2024/01/09 - 04:44:02 | 202401090444011098615121dqEj648 | relay error (channel #195): json: cannot unmarshal string into Go struct field Embedding.data.embedding of type []float64 

```

原先使用原作者的好像没有这个问题

**Comment by MartialBE** [comment]
我这里测试OpenAI可以正常调用。
你使用的是什么模型？ 是所有的都会调用失败吗？还是固定某些失败？

**Comment by woodchen-ink** [comment]
> 我这里测试OpenAI可以正常调用。 你使用的是什么模型？ 是所有的都会调用失败吗？还是固定某些失败？

text-embedding-ada-002，全失败，很奇怪，我再测下

**Comment by woodchen-ink** [comment]
再测没问题，可能是我上一个调用方式的问题

**Comment by MartialBE** [comment]
我知道是为什么了，你应该设置了`"encoding_format": "base64"`  导致报错了。
现在解决了

**Comment by woodchen-ink** [comment]
> 我知道是为什么了，你应该设置了`"encoding_format": "base64"` 导致报错了。 现在解决了

搜嘎，谢谢
