### ISSUE TITLE
首页看板增加周、月维度统计

### ISSUE THREAD

**Issue by Timoshao** [MartialBE/one-api#32]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
首页看板增加周、月维度统计
**应用场景**
目前仅有当天的数据统计，过了当天无法查看，希望增加周和月维度统计，如果能根据时间周期筛选更好

**Comment by MartialBE** [comment]
首页统计卡片是最近7天的数据都可以查看。 卡片旁边有条形图。鼠标放上去就可以查看。

月统计加上也很简单。只不过如果使用人多的话对数据库也是会造成压力的。

**Comment by woodchen-ink** [comment]
月的话压力的确大了，个人觉得可以做成一个 ***，点击的时候再统计

**Comment by MartialBE** [comment]
添加了一个管理员的统计页面。

#59
