### ISSUE TITLE
Azure Openai无法正常使用

### ISSUE THREAD

**Issue by mouxangithub** [MartialBE/one-api#40]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
Azure请求报错，无法正常使用，我切回原版one-api是可以使用的，用的docker部署

```shell
{
  "error": {
    "message": "Panic detected, error: interface conversion: interface {} is string, not int. Please submit a issue here: https://github.com/songquanpeng/one-api",
    "type": "one_api_panic"
  }
}
```

**Comment by MartialBE** [comment]
麻烦提供一下调用的接口以及参数。
应该不是所有的模型都报错，因为我主力用的也是`Azure OpenAI`
