### ISSUE TITLE
修改了逻辑后，套中转时无法查额度了

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-api#45]
![image](https://github.com/MartialBE/one-api/assets/95951386/feab7607-7d18-446a-ba73-978df6f8f015)

我觉得这个查余额在自定义渠道还是得保留，按照旧版OPENAI的方式请求

**Comment by MartialBE** [comment]
好的。我看看。
供应商这块代码我又重构了一遍。之前的有些逻辑可能被移除了。

**Comment by woodchen-ink** [comment]
尴尬，我使用的是自定义，因为我没用预置的代理平台

**Comment by woodchen-ink** [comment]
也许自定义可以允许查余额，因为自定义肯定都是openai的方式去请求的

**Comment by MartialBE** [comment]
现在已经修复了。你再试试
