### ISSUE TITLE
最新版没有流式输出了

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-api#46]
很奇怪，为啥没流式输出了呢，现在是15个字左右一起出，有修改这部分逻辑吗？

**Comment by MartialBE** [comment]
是的，这次重构主要就是对流式输出进行更改，做成通用的调用方式。
我这边测试是正常的。
你是否是使用`Azure OpenAI`？ 它的输出因为有内容过滤并不是实时的，会导致等待多个文字后才会输出。OpenAI的就不会。

**Comment by woodchen-ink** [comment]
> 是的，这次重构主要就是对流式输出进行更改，做成通用的调用方式。 我这边测试是正常的。 你是否是使用`Azure OpenAI`？ 它的输出因为有内容过滤并不是实时的，会导致等待多个文字后才会输出。OpenAI的就不会。

我使用的是openai的，azure的我知道不是流式输出

**Comment by MartialBE** [comment]
stream输出就是一段一段的输出。
你是用软件还是API测试的？
你是想说现在比之前反应要慢吗？

**Comment by zaite** [comment]
流式输出改成了一段话一段话的输出，阅读体验感下降了，能不能优化一下，对比下还是老版本的输出方式好用，对阅读友好，在回复速度上明显感觉慢了很多（应该是这种新的输出方式造成了）

**Comment by woodchen-ink** [comment]
> 流式输出改成了一段话一段话的输出，阅读体验感下降了，能不能优化一下，对比下还是老版本的输出方式好用，对阅读友好，在回复速度上明显感觉慢了很多（应该是这种新的输出方式造成了）

+1

**Comment by MartialBE** [comment]
@woodchen-ink 
修复了， 你可以拉取最新的 dev镜像试试看还有没有问题。

https://github.com/MartialBE/one-api/assets/42402987/dd5ed000-3013-4c67-99b1-346fd2fd262c

**Comment by woodchen-ink** [comment]
> @woodchen-ink 修复了， 你可以拉取最新的 dev镜像试试看还有没有问题。
> 
>  2024-01-25.12.03.08.mp4

谢谢，我看代码这次还是个大工程呢，我拉取测试下

**Comment by MartialBE** [comment]
对`Azure OpenAI`也做了处理， 现在也能实现 打字机效果了。

**Comment by woodchen-ink** [comment]
> 对`Azure OpenAI`也做了处理， 现在也能实现 打字机效果了。

厉害👍，我试试

**Comment by woodchen-ink** [comment]
![20240125132011_rec_](https://github.com/MartialBE/one-api/assets/95951386/f5d08139-c19f-4b41-ae4b-627841e423be)
我还是没有呢，甚至容器报错了
![image](https://github.com/MartialBE/one-api/assets/95951386/72433c49-0519-4d8a-8f60-3d8b9c810427)

**Comment by MartialBE** [comment]
好奇怪，我使用你的镜像 OpenAI  / azure都能正常输出打字机效果，  
1. 你是使用OpenAI 官方的接口吗？ 如果不是官方的接口，你看方便给我一个`key`测试一下？ email: [buer@xiao5.info](mailto:buer@xiao5.info)
2. 你是直接部署在本地吗？还是在服务器上？ 如果是在服务器上的话，那直接在本地部署调用会有这种问题吗？

下面这个报错是因为 渠道代理地址 有问题，你是使用什么数据库？
你查看一下你的数据库 `channel`表中的 `proxy`字段 是否有为 `null` 的值？ 
如果没有代理，这个值应该是 空字符串 而不是 `null`， 你可以手动改过来。 并查看一下表结构 `proxy`字段的默认值是否是 空字符串。

**Comment by woodchen-ink** [comment]
> 好奇怪，我使用你的镜像 OpenAI / azure都能正常输出打字机效果，
> 
> 1. 你是使用OpenAI 官方的接口吗？ 如果不是官方的接口，你看方便给我一个`key`测试一下？ email: [buer@xiao5.info](mailto:buer@xiao5.info)
> 2. 你是直接部署在本地吗？还是在服务器上？ 如果是在服务器上的话，那直接在本地部署调用会有这种问题吗？
> 
> 下面这个报错是因为 渠道代理地址 有问题，你是使用什么数据库？ 你查看一下你的数据库 `channel`表中的 `proxy`字段 是否有为 `null` 的值？ 如果没有代理，这个值应该是 空字符串 而不是 `null`， 你可以手动改过来。 并查看一下表结构 `proxy`字段的默认值是否是 空字符串。

非常感谢帮忙排查，我似乎明白问题所在了。上个版本因为proxy url无法修改，我在数据库进行编辑的，我删除后自动变成了`null`，并且前两天我从自建服务器迁移回了香港云服务器，mysql版本也从mysql8.2变为了mariadb10.4.19，所以造成了这个问题。

我使用的是OPENAI官方接口，我先自己测试下，如果打字机效果还有问题，我会给你发邮件。

再次感谢
