### ISSUE TITLE
bug: 代理地址无法删除

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-api#48]
![image](https://github.com/MartialBE/one-api/assets/95951386/e85a2dcd-ec8b-4858-8a1c-efc973d9aaa9)
此处一旦设置了，无法删除

**Comment by woodchen-ink** [comment]
![image](https://github.com/MartialBE/one-api/assets/95951386/c8c22469-472d-4d7b-a8a7-0466537851ad)

**Comment by MartialBE** [comment]
emmmm。你不是我都没注意... 这应该是一个存在很久的bug了...

**Comment by MartialBE** [comment]
已修复

**Comment by AlanWang2333** [comment]
> ![image](https://private-user-images.githubusercontent.com/95951386/298203022-e85a2dcd-ec8b-4858-8a1c-efc973d9aaa9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MDY3MjgsIm5iZiI6MTcyMjkwNjQyOCwicGF0aCI6Ii85NTk1MTM4Ni8yOTgyMDMwMjItZTg1YTJkY2QtZWM4Yi00ODU4LThhMWMtZWZjOTczZDlhYWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAxMDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmYzU5OTliNWNjNmJjN2NjNmE4MTc2MTJjNmQ3M2QxMDhmMDA5YTYwNDlkZDU4ZWE0OWNjYzc5ZmY4ZmU1ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6GOpMFLS1l-33UWnNo5EkjN0DvQSUOQYJqzocR4gdCI) 此处一旦设置了，无法删除

请问怎么在vps上部署http代理

**Comment by woodchen-ink** [comment]
> > ![image](https://private-user-images.githubusercontent.com/95951386/298203022-e85a2dcd-ec8b-4858-8a1c-efc973d9aaa9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MDY3MjgsIm5iZiI6MTcyMjkwNjQyOCwicGF0aCI6Ii85NTk1MTM4Ni8yOTgyMDMwMjItZTg1YTJkY2QtZWM4Yi00ODU4LThhMWMtZWZjOTczZDlhYWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAxMDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmYzU5OTliNWNjNmJjN2NjNmE4MTc2MTJjNmQ3M2QxMDhmMDA5YTYwNDlkZDU4ZWE0OWNjYzc5ZmY4ZmU1ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6GOpMFLS1l-33UWnNo5EkjN0DvQSUOQYJqzocR4gdCI) 此处一旦设置了，无法删除
> 
> 请问怎么在vps上部署http代理

https://q58.org/questions/D1t3

**Comment by AlanWang2333** [comment]
十分感谢
