### ISSUE TITLE
流式输出改成了一段话一段话的输出，阅读体验感下降了

### ISSUE THREAD

**Issue by zaite** [MartialBE/one-api#51]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

**流式输出改成了一段话一段话的输出，阅读体验感下降了，能不能优化一下，对比下还是老版本的输出方式好用，对阅读友好，在回复速度上明显感觉慢了很多（应该是这种新的输出方式造成了）**

**复现步骤**

**预期结果**

**相关截图**

**Comment by MartialBE** [comment]
我检查一下看看是哪里有什么问题。

**Comment by zaite** [comment]
https://github.com/MartialBE/one-api/assets/22079456/07414cb9-0a0f-4ed6-8689-3582b62ae31b
录了段视频供参考，使用到以下模型：
![image](https://github.com/MartialBE/one-api/assets/22079456/4ea447df-da9e-45e8-b569-83a19a7e36d2)

**Comment by MartialBE** [comment]
明白了， 因为我这边访问速度的原因，我没感知到， 我大概知道问题出在哪里了。

**Comment by MartialBE** [comment]
修复了， 你可以拉取最新的 dev镜像试试看还有没有问题。

https://github.com/MartialBE/one-api/assets/42402987/dd5ed000-3013-4c67-99b1-346fd2fd262c

**Comment by zaite** [comment]
似乎还是有问题下面是pull的镜像详情和使用的模型：
![image](https://github.com/MartialBE/one-api/assets/22079456/63cb64d0-2b3a-4bd0-bc30-6fcbc2dc75ff)
![image](https://github.com/MartialBE/one-api/assets/22079456/7f555ad2-2417-44e1-a3f8-9dec014904d9)

重新部署后还是没有打字机效果：

[视频链接](https://github.com/MartialBE/one-api/assets/22079456/f85ddec1-ee1d-4086-a9ae-d8d6f25a3186)

**Comment by MartialBE** [comment]
你是否正在使用 `ERNIE-Bot`？这种情况确实会发生，因为它的输出是按段输出的。我测试过原版的`one-api`，效果也是一样的。

打字机效果的前提是，在使用`stream`时，`api`接口需要一个字一个字的输出，这样才能产生打字机效果。
然而，`文心一言`的`API`在使用`stream`时，是以几个字为单位输出的。这就导致了这种输出效果。
只要大模型官方`api`的`stream`输出没有按照一个字一个字输出的，都会有这样的效果。

另外，虽然打字机效果看起来很流畅，但实际上，请求输出的时间会更长。

**Comment by zaite** [comment]
上面使用的是ERNIE-Bot，ERNIE-Bot 4.0也是这样，刚我试了下智谱的，好像反应快点，但还是分段输出：

[视频链接](https://github.com/MartialBE/one-api/assets/22079456/9e095bff-23f8-415d-9de2-ebcb8bed55d6)

**Comment by MartialBE** [comment]
这是正常的， 国内的大模型stream输出基本都是几个字一起返回，自然没有 打字机效果。
你可以直接调用他们的API查看他们的区别。
如果要实现这种效果也可以实现，但是我觉得没有很大的必要。

这是直接调用`OpenAI`的stream输出：
<img width="515" alt="iShot_2024-01-29_11 09 33" src="https://github.com/MartialBE/one-api/assets/42402987/6470cbb0-21f9-4741-aa38-797281068c67">


这是直接调用`zhipu` API的 stream输出：
<img width="591" alt="iShot_2024-01-29_11 06 42" src="https://github.com/MartialBE/one-api/assets/42402987/736eaeca-7128-48e5-a4ce-be8f4efe1b6c">

这是直接调用`Qwen` API的stream输出：
<img width="535" alt="iShot_2024-01-29_11 06 11" src="https://github.com/MartialBE/one-api/assets/42402987/ea9121ad-420e-41bb-8759-42c743efc709">

**Comment by zaite** [comment]
很奇怪，前面几个版本是重新处理了下stream输出吗，我记得更新新版之前还是原版oneapi国内模型也是支持stream输出打字机效果的。百度模型调用很慢，段式输出的效果一下子就体验感很差了，智谱的反应速度还好，段式也还凑合

**Comment by MartialBE** [comment]
`zhipu` 这边使用了 `v4`版本的 `API`，输出速度好像变快了。
输出速度快，也会造成一段一段卡顿的感觉， 就像`Azure OpenAI` 一样。
不过也可以通过负优化来实现，打字机效果。
我“优化”了一下， 你等`GitHub Action`编译好之后，可以拉取`dev`镜像再试试。 
对比对比`zhipu`前一版和现在这边两者 哪个更好一些。

**Comment by zaite** [comment]
好，我再试试 [抱拳]

**Comment by zaite** [comment]
打字机效果，智谱的可以了，但是出来的很快，可以再加点延时，总体来说今天的版本感觉好多了

**Comment by MartialBE** [comment]
emmm，如果把请求时长拉太长的话，占用请求数对服务器也有压力的。
我觉得能输出打字机效果。用户体验好一些就好了。不要太强求完美的输出了。
当然你自用或者愿意牺牲性能换取体验，可以fork代码自己拉长一下时长。

**Comment by MartialBE** [comment]
另： 你可以换zhipu的模型了。新接口对老模型支持并不友好。可能随时取消支持

**Comment by zaite** [comment]
ok
