### ISSUE TITLE
直接使用智谱渠道大模型chatglm_turbo有问题

### ISSUE THREAD

**Issue by zaite** [MartialBE/one-api#52]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
使用fastgpt 进行对接，如直接使用智谱渠道的chatglm_turbo模型，fastgpt提示：1214 history参数非法，

使用songquanpeng/one-api版oneapi则正常/使用三方代理渠道调用chatglm_turbo则正常

**复现步骤**

**预期结果**

**相关截图**
![image](https://github.com/MartialBE/one-api/assets/22079456/fcfc202b-de83-413d-808f-942add33298c)

**Comment by zaite** [comment]
已经排查到问题，非系统bug

**Comment by zaite** [comment]
> 测试使用的是百度Embedding-V1

**Comment by MartialBE** [comment]
zhipu 的 API接口 升级到 `v4`版本了， 
你这个的问题应该是 使用旧模型时， 同时发送两个 助手信息，或者同时发送两个用户信息 导致的报错， 新模型不会出现这个问题：
<img width="1549" alt="iShot_2024-01-25_11 45 49" src="https://github.com/MartialBE/one-api/assets/42402987/2aafd4e4-752b-4ec4-beae-e60b9bbe0f0c">

<img width="1528" alt="iShot_2024-01-25_11 46 39" src="https://github.com/MartialBE/one-api/assets/42402987/3d0cab4b-3aeb-4aaa-8c8b-1d9e1f2828a1">

你将 `chatglm_turbo` 更换至 `glm-3-turbo` 再试试。
v4版本 官方文档已经不存在 `chatglm_xxx`模型了， 对应的是vision 模型 ： `cogview-3` ，chat模型：`glm-3-turbo``glm-4`， embedding模型： embedding-2
