### ISSUE TITLE
请求key的时候，携带渠道id会报错

### ISSUE THREAD

**Issue by mouxangithub** [MartialBE/one-api#55]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x ] 我已确认目前没有类似 issue
+ [ x] 我已确认我已升级到最新版本
+ [ x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
当请求头Key的时，携带渠道id会报错，Bearer sk-xxxx-1，原版one-api是可以的
接口返回
```shell
{
	"error": {
		"message": "Panic detected, error: interface conversion: interface {} is string, not int. Please submit a issue here: https://github.com/songquanpeng/one-api",
		"type": "one_api_panic"
	}
}
```

另外，请求微软openai的gpt-4的时候，回复的信息好像没回复完整，出现断句了，我用原版one-api也会，不知道大佬能否修复下，用的瑞典中部地区，api版本是2023-12-01-preview

**Comment by MartialBE** [comment]
已修复。 
我也是瑞典中部的， 是正常输出。
断句可能是你内容过滤设置的问题？ 现在可以将内容过滤放宽了，你试试

<img width="1013" alt="iShot_2024-01-26_17 14 54" src="https://github.com/MartialBE/one-api/assets/42402987/a7eb63d7-60d0-4848-bba5-7f844e9c7fe5">

**Comment by mouxangithub** [comment]
好的，感谢，用渠道id已可以请求，但azure的gpt4好像还是出现短句，并未创建过滤器，用官方api请求是正常能走通的，不知道为什么用one-api就不行

![image](https://github.com/MartialBE/one-api/assets/48978046/1e2dfb3f-7249-4d4d-8e52-bb0eb693772d)

**Comment by MartialBE** [comment]
你看看你返回参数中的`content_filter_results` 有没有显示`true`的内容？ 如果有那么说明触发了 过滤器。

你没有创建内容过滤，那么就是使用 `Azure`默认的内容过滤器，是比较严格的。
你可以去`Azure OpenAI Studio` - 内容筛选器（预览）- 创建自定义内容筛选器
在`配置筛选器` 中将所有的选项拉到`高` ， 其他直接不动，保存。
然后去`部署`中， 编辑每一个模型， 选择`高级选项`- 内容筛选器 。 选择你刚刚创建的那个筛选器，保存。

你可以尝试一下， 因为`Azure`默认的过滤器有点迷， 有时候很正常的文字也会触发。

**Comment by mouxangithub** [comment]
> 你看看你返回参数中的`content_filter_results` 有没有显示`true`的内容？ 如果有那么说明触发了 过滤器。
> 
> 你没有创建内容过滤，那么就是使用 `Azure`默认的内容过滤器，是比较严格的。 你可以去`Azure OpenAI Studio` - 内容筛选器（预览）- 创建自定义内容筛选器 在`配置筛选器` 中将所有的选项拉到`高` ， 其他直接不动，保存。 然后去`部署`中， 编辑每一个模型， 选择`高级选项`- 内容筛选器 。 选择你刚刚创建的那个筛选器，保存。
> 
> 你可以尝试一下， 因为`Azure`默认的过滤器有点迷， 有时候很正常的文字也会触发。

好像确实是如此，按照你的方法进行配置了就可以正常使用了，感谢感谢，get到了

**Comment by xixia123** [comment]
我在尝试请求特定渠道的模型时，API KEY设置渠道ID，请求接口/v1/models，得到了相同的报错，使用的是0.14.1版本的OneHub
