### ISSUE TITLE
请求功能

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-api#72]
一直想实现一个功能

就是当用户请求失败的时候，能否把docker里的那种失败日志显示到日志处，最好能显示请求的url，请求信息，请求方式等完整信息。

![image](https://github.com/MartialBE/one-api/assets/95951386/95d6e113-0c4e-47d9-b69e-e05475f95e8c)

因为之前有朋友用，调用一直失败，我每次都要从docker日志里翻好久才能找到对应的报错信息，然后去排查，甚至还找不到原因。最后是通过cloudflare gateway的日志查到具体的原因的。

我的实力不济，想不到实现方法，不知道作者有没有想法 😁

**Comment by MartialBE** [comment]
后面考虑加上。
现在准备先写几个工具类型的功能。
渠道一多好难管理，渠道有哪些模型/azure api 版本替换 /批量删除添加模型 等等。

**Comment by woodchen-ink** [comment]
好的，谢谢。 批量管理也是痛点，大佬加油

**Comment by MartialBE** [comment]
这个错误日志我想了一下，如果写入到 日志里面会产生大量的数据，感觉很没有必要。 
一般在使用第三方软件过程中应该不会出现问题，如果是自己调试，自己也可以在程序中直接打日志来发现错误。
暂时我还不考虑增加这个错误日志的记录。
如果你想添加，我可以给你一个超简单的思路：

1. 在`middleware`文件夹中添加一个中间件：
```go
func DebugLogger() gin.HandlerFunc {
    return func(c *gin.Context) {
        // 记录请求值
        requestBody, _ := ioutil.ReadAll(c.Request.Body)
        c.Request.Body = ioutil.NopCloser(bytes.NewBuffer(requestBody)) // 重要：复制体以便后续处理
        log.Printf("Request Body: %s\n", string(requestBody))

        // 记录响应值
        writer := &debugLogWriter{body: bytes.NewBufferString(""), ResponseWriter: c.Writer}
        c.Writer = writer

        c.Next() // 处理请求

        log.Printf("Response Body: %s\n", writer.body.String())

        // TODO: 保存/处理日志逻辑
    }
}

type debugLogWriter struct {
    gin.ResponseWriter
    body *bytes.Buffer
}

func (w debugLogWriter) Write(b []byte) (int, error) {
    w.body.Write(b)
    return w.ResponseWriter.Write(b)
}

```

2.  在`router/relay-router.go`的`relayV1Router`使用上面的中间件

这样就能完整的记录用户的请求和响应了。 不过这样也会占用大量系统资源，最好做一个开关。
你也要注意，有些请求是图片/音频， 很大。你可以在中间件中判断哪些记录哪些不记录

**Comment by woodchen-ink** [comment]
> 这个错误日志我想了一下，如果写入到 日志里面会产生大量的数据，感觉很没有必要。 一般在使用第三方软件过程中应该不会出现问题，如果是自己调试，自己也可以在程序中直接打日志来发现错误。 暂时我还不考虑增加这个错误日志的记录。 如果你想添加，我可以给你一个超简单的思路：
> 
> 1. 在`middleware`文件夹中添加一个中间件：
> 
> ```go
> func DebugLogger() gin.HandlerFunc {
>     return func(c *gin.Context) {
>         // 记录请求值
>         requestBody, _ := ioutil.ReadAll(c.Request.Body)
>         c.Request.Body = ioutil.NopCloser(bytes.NewBuffer(requestBody)) // 重要：复制体以便后续处理
>         log.Printf("Request Body: %s\n", string(requestBody))
> 
>         // 记录响应值
>         writer := &debugLogWriter{body: bytes.NewBufferString(""), ResponseWriter: c.Writer}
>         c.Writer = writer
> 
>         c.Next() // 处理请求
> 
>         log.Printf("Response Body: %s\n", writer.body.String())
> 
>         // TODO: 保存/处理日志逻辑
>     }
> }
> 
> type debugLogWriter struct {
>     gin.ResponseWriter
>     body *bytes.Buffer
> }
> 
> func (w debugLogWriter) Write(b []byte) (int, error) {
>     w.body.Write(b)
>     return w.ResponseWriter.Write(b)
> }
> ```
> 
> 2. 在`router/relay-router.go`的`relayV1Router`使用上面的中间件
> 
> 这样就能完整的记录用户的请求和响应了。 不过这样也会占用大量系统资源，最好做一个开关。 你也要注意，有些请求是图片/音频， 很大。你可以在中间件中判断哪些记录哪些不记录

占用资源的问题也对，对数据库的压力也会很大，我考虑考虑，多谢建议
