### ISSUE TITLE
dall-e绘图的计费错误问题

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-api#73]
![image](https://github.com/MartialBE/one-api/assets/95951386/fb5ddfed-2b84-45f0-8cfd-aa8f08a1f765)
![image](https://github.com/MartialBE/one-api/assets/95951386/f14da520-d988-411a-8bcc-b202330f3cc2)

计费好像有问题

是我的问题吗，兄弟你那边测下准不

**Comment by woodchen-ink** [comment]
![image](https://github.com/MartialBE/one-api/assets/95951386/ffe81495-04c7-4c1a-97f2-025414c8fc78)
相关代码我没改呢....

**Comment by MartialBE** [comment]
修改完成倍率时。计算公式搞错了。
所有的模型计费都有问题。请及时更新。
