### ISSUE TITLE
模型映射功能失效

### ISSUE THREAD

**Issue by YanxingLiu** [MartialBE/one-api#78]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
渠道模型映射功能失效
**复现步骤**
以千问turbo为例：
<img width="856" alt="image" src="https://github.com/MartialBE/one-api/assets/42299757/ec344203-a550-4ec1-b80d-6fdb0cc502d9">
将qwen-turbo映射到qwen-test
**预期结果**
调用openai的获取模型列表api，发现返回的仍然是qwen-turbo，并且并没有qwen-test的模型
<img width="883" alt="image" src="https://github.com/MartialBE/one-api/assets/42299757/15a72f92-c96d-47e0-ab30-9c8749bd953f">

**Comment by MartialBE** [comment]
除了在模型映射填写 test以外。还需要在上面的模型中添加test。

上面填写的模型是用户允许访问的模型。
下面的模型映射是用户访问允许的模型后映射成另一个模型。

**Comment by 3377** [comment]
1、我也碰到这个问题了，一度以为是BUG，调试了一个多小时。这个问题在文档里面没写，直到找到这来才算明白。
2、建议这个参考chatnio，很好用，不用写json，只需要些：请求名>渠道名，前面写！就表示渠道名不用重复被获取。
3、当前按照此方式可以获取自定义的模型名称了，但是原始的还在，当API一多就混乱无比。
建议优化，当然，仅仅是建议。@MartialBE
