### ISSUE TITLE
glm-4-vision网络错误

### ISSUE THREAD

**Issue by YanxingLiu** [MartialBE/one-api#80]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整查看过项目 README，尤其是常见问题部分
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
glm4-vision vqa后端报告出现网络错误。 Gemini-pro-vision可以正常使用
GLM4-Vision
<img width="1708" alt="image" src="https://github.com/MartialBE/one-api/assets/42299757/f1a3c97a-c369-4e7a-b0af-0e06f56aa283">
gemini-pro-vision
<img width="2048" alt="image" src="https://github.com/MartialBE/one-api/assets/42299757/9add9058-3076-4739-80c2-f7e7affc0907">

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by MartialBE** [comment]
这是因为，`Next`,`Lobe` 这些客户端的图片都是以`base64`形式传入的。
而`glm-4-vision`， `通义千问VL`这些国产的vision模型，只支持 `url`形式的图片，所以无法使用。

**Comment by MartialBE** [comment]
咦，`glm-4-vision`好像是可以支持的，需要吧格式改一下。 我看看

**Comment by MartialBE** [comment]
试试 应该可以了

![image](https://github.com/MartialBE/one-api/assets/42402987/886dc0e9-954e-41bc-9491-bb029a55c801)

**Comment by YanxingLiu** [comment]
> 试试 应该可以了
> 
> ![image](https://private-user-images.githubusercontent.com/42402987/309239115-886dc0e9-954e-41bc-9491-bb029a55c801.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTY2ODYsIm5iZiI6MTcwOTI5NjM4NiwicGF0aCI6Ii80MjQwMjk4Ny8zMDkyMzkxMTUtODg2ZGMwZTktOTU0ZS00MWJjLTk0OTEtYmIwMjlhNTVjODAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDEyMzMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5M2ZiZDNhOTMyMzdmNjMxZmU1NWUyNWY0ZmZkNTFhZWMyZmRkYWNhM2M5NjMzMzU3MjRlYTI3MmRmODcxODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.arnOS2ws2wfwOq26lW8dmCnyMrqtYZ4s_-Us0CRm28M)

好的，我试试，谢谢你！

**Comment by YanxingLiu** [comment]
> 试试 应该可以了
> 
> ![image](https://private-user-images.githubusercontent.com/42402987/309239115-886dc0e9-954e-41bc-9491-bb029a55c801.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTY2ODYsIm5iZiI6MTcwOTI5NjM4NiwicGF0aCI6Ii80MjQwMjk4Ny8zMDkyMzkxMTUtODg2ZGMwZTktOTU0ZS00MWJjLTk0OTEtYmIwMjlhNTVjODAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDEyMzMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5M2ZiZDNhOTMyMzdmNjMxZmU1NWUyNWY0ZmZkNTFhZWMyZmRkYWNhM2M5NjMzMzU3MjRlYTI3MmRmODcxODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.arnOS2ws2wfwOq26lW8dmCnyMrqtYZ4s_-Us0CRm28M)

好的，我试试，感谢！
