### ISSUE TITLE
请问智谱怎么开启联网？

### ISSUE THREAD

**Issue by Bossjava** [MartialBE/one-api#82]
请问智谱怎么开启联网？
谢谢

**Comment by Bossjava** [comment]
另外，后台好像看不到当前的版本，不知道容器更新成功没，还是我没找对位置呀？

**Comment by MartialBE** [comment]
智谱的`web_search` 还没有加上。
后台暂时还没显示版本号，后面会处理的。

**Comment by MartialBE** [comment]
@Bossjava 
现在可以直接在渠道中配置插件信息了， 目前支持`智谱` 和 `qwen`的插件配置  #89
不过 智谱的API设置`web_search`好像有点问题，开启和关闭没区别，并没有进行联网。
它的`知识库` 是可以使用的。
