### ISSUE TITLE
请问已经部署好的系统怎么和你保持同步更新呢？

### ISSUE THREAD

**Issue by caochengchen** [MartialBE/one-api#83]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，尤其是常见问题部分
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈 
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

**复现步骤**

**预期结果**

**相关截图**
如果没有的话，请删除此节。

**Comment by MartialBE** [comment]
你可以定时拉取docker。
也可以`fork`一份代码，通过GitHub Actions， 定时同步/编译然后自动部署到你的服务器上。
如果使用的云服务，`fork`一份代码后，在对应平台绑定你的仓库，之后你的仓库同步代码后就会自动部署了。

**Comment by 2277419213** [comment]
> 你可以定时拉取docker。 也可以`fork`一份代码，通过GitHub Actions， 定时同步/编译然后自动部署到你的服务器上。 如果使用的云服务，`fork`一份代码后，在对应平台绑定你的仓库，之后你的仓库同步代码后就会自动部署了。

大佬，一开始容器部署了，有没有更新命令，原版的好像有，适用我们这个么

**Comment by Akuns** [comment]
> > 你可以定时拉取docker。 也可以`fork`一份代码，通过GitHub Actions， 定时同步/编译然后自动部署到你的服务器上。 如果使用的云服务，`fork`一份代码后，在对应平台绑定你的仓库，之后你的仓库同步代码后就会自动部署了。
> 
> 大佬，一开始容器部署了，有没有更新命令，原版的好像有，适用我们这个么

同问+1，我也遇到这个问题了
