### ISSUE TITLE
渠道批量处理处  能否添加映射关系

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-api#84]
如题

因为我想把gpt-3.5-turbo全部映射到0125去

4.0也映射到 4-turbo去

如果可以批量管理，可能会方便一些。

但是又可能会涉及到部分渠道单独设置，不知道怎么弄比较好

不知道作者觉得这个有没有必要呢

**Comment by MartialBE** [comment]
映射批量有点繁琐了。因为映射在数据库存储的是json字符串，而字段类型是text，不好搜索...

**Comment by chawaa** [comment]
请求添加 原one api 批量添加渠道功能

**Comment by woodchen-ink** [comment]
> 映射批量有点繁琐了。因为映射在数据库存储的是json字符串，而字段类型是text，不好搜索...

OKK

**Comment by MartialBE** [comment]
> 请求添加 原one api 批量添加渠道功能

加上了。

**Comment by MartialBE** [comment]
> > 映射批量有点繁琐了。因为映射在数据库存储的是json字符串，而字段类型是text，不好搜索...
> 
> 
> 
> OKK

这个东西我也想了好久。 还没想到一个好的方式。
我本想学其他项目的做法，通过创建 模型名称，模型名称绑定渠道。每个渠道可以定义单独的优先级和权重。
但是这样做的话添加模型就非常麻烦了。要添加很多个。但是可以很灵活。

如果兼容现有的做法，又因为渠道 直接可以添加修改 分组 模型 优先级 权重 映射。 逻辑就不自洽了。

**Comment by MartialBE** [comment]
> > 映射批量有点繁琐了。因为映射在数据库存储的是json字符串，而字段类型是text，不好搜索...
> 
> 
> 
> OKK

这个东西我也想了好久。 还没想到一个好的方式。
我本想学其他项目的做法，通过创建 模型名称，模型名称绑定渠道。每个渠道可以定义单独的优先级和权重。
但是这样做的话添加模型就非常麻烦了。要添加很多个。但是可以很灵活。

如果兼容现有的做法，又因为渠道 直接可以添加修改 分组 模型 优先级 权重 映射。 逻辑就不自洽了。

**Comment by woodchen-ink** [comment]
> > > 映射批量有点繁琐了。因为映射在数据库存储的是json字符串，而字段类型是text，不好搜索...
> > 
> > 
> > OKK
> 
> 这个东西我也想了好久。 还没想到一个好的方式。 我本想学其他项目的做法，通过创建 模型名称，模型名称绑定渠道。每个渠道可以定义单独的优先级和权重。 但是这样做的话添加模型就非常麻烦了。要添加很多个。但是可以很灵活。
> 
> 如果兼容现有的做法，又因为渠道 直接可以添加修改 分组 模型 优先级 权重 映射。 逻辑就不自洽了。

第一种方式听起来很好，但是业务逻辑完全要重构了，初始化的时候会有点麻烦，但是如果设置好了以后，后面变动就会方便。并且模型直接内置模型，通过模型绑定渠道的时候可以直接在弹出框里勾选多个渠道。

目前的方式也可以用，毕竟修改次数没那么多。

也许可以基于其他方向选择，比如性能。

两种方式的性能呢？哪一种的性能会更好

**Comment by MartialBE** [comment]
性能其实是一样的 不用重构。
渠道选择的模型 分组 都存储在 ability 表中。
只要更改存储逻辑 和前端显示就能实现。

**Comment by woodchen-ink** [comment]
> 性能其实是一样的 不用重构。 渠道选择的模型 分组 都存储在 ability 表中。 只要更改存储逻辑 和前端显示就能实现。

emm，那我给不了什么意见了。 

有时间也许可以试试改一下第一种，感觉会有意思一点
