### ISSUE TITLE
生成key时限制渠道使用

### ISSUE THREAD

**Issue by 929496959** [MartialBE/one-api#88]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ x ] 我已确认目前没有类似 issue
+ [ x ] 我已确认我已升级到最新版本
+ [ x ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ x ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ x ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
      当有多个渠道时,我想指定key 只能使用 其中的几个不全部使用

**Comment by MartialBE** [comment]
这个需求的使用场景是什么？

**Comment by 929496959** [comment]
区分办公和自己私人的渠道

**Comment by MartialBE** [comment]
分组可以满足你的需求了。
因为如果有人搭建商用的话，在创建key的时候不可能让用户知道平台有哪些渠道。
对用普通用户来说，他们只要知道哪些模型可用。
所以暂时不考虑这样做。

**Comment by 929496959** [comment]
好的 感谢
