### ISSUE TITLE
余额好像不显示了

### ISSUE THREAD

**Issue by kokojacket** [MartialBE/one-api#9]
原来是显示的，切换为您的镜像之后不显示余额了，使用的是中转api。songquanpeng/one-api镜像可以显示这个余额
![image](https://github.com/MartialBE/one-api/assets/74887370/5a6cd03a-7e82-4225-8f48-d0c9326bb461)

**Comment by MartialBE** [comment]
已修复， 拉取 最新代码编译 或者 docker的dev版本。
PS： 余额操作这边我和上游不一样了， 但是我这边的渠道都是不支持 余额查询的，所以这块没有验证， 可能还存在某些问题。
