### ISSUE TITLE
请求支持Mistral API 

### ISSUE THREAD

**Issue by Gogoworks** [MartialBE/one-api#90]
**例行检查**

[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整查看过项目 README，已确定现有版本无法满足需求
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**功能描述**
官网:  https://mistral.ai/

文档: https://docs.mistral.ai/

目前最新模型:  mistral-large-2402 

**应用场景**

**Comment by MartialBE** [comment]
已添加，这个模型的函数调用能力也太差了吧... 上次这么差的 还是讯飞。 而且整个话痨 -。-

**Comment by Gogoworks** [comment]
哈哈哈,的确有点不尽人意.不过他们进步的很快.

**Comment by MartialBE** [comment]
没有。可以先用dev版

**Comment by Gogoworks** [comment]
> 没有。可以先用dev版

dev版 docker版本号? 如何拉取?

**Comment by MartialBE** [comment]
是的 

docker pull ghcr.io/martialbe/one-api:dev
或者

docker pull martialbe/one-api:dev
