### ISSUE TITLE
乐

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-api#96]
![img_v3_028r_fd92c599-0376-4595-b535-9334bc76062g](https://github.com/MartialBE/one-api/assets/95951386/20928ddd-a37f-4796-958f-d561015c5a32)

**Comment by MartialBE** [comment]
已更新模型名称。
百度这个模型名称真的混乱， 一下用 `_` 一下用 `-`

**Comment by woodchen-ink** [comment]
> 已更新模型名称。 百度这个模型名称真的混乱， 一下用 `_` 一下用 `-`

哈哈，谁说不是，阿里换过一次还好说，百度换两次了，难不成是为了 3.5 和 4 的搜索词？ 🐶
