### ISSUE TITLE
帮忙支持下claude的cf gateway

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-api#97]
![image](https://github.com/MartialBE/one-api/assets/95951386/cec4301e-6875-4d31-99ff-0dad10cc178e)

``` bash
curl -X POST https://gateway.ai.cloudflare.com/v1/feedd0aaxxxxxxxxxxxx/xxxx/anthropic/messages \
    -H 'x-api-key: XXX' \
    -H "anthropic-version: 2023-06-01" \
    -H 'Content-Type: application/json' \
    -d '{
      "model": "claude-3-opus-20240229",
      "max_tokens": 1024,
      "messages": [
          {"role": "user", "content": "Hello, world"}
      ]
    }'
```

我想用claude,但是我是香港的机器, 目前是通过部署一个clash, 通过代理去访问的哈哈

我发现cf gateway支持claude了, 可以帮忙添加一下吗? 毕竟用cf gateway不担心封号. 只是估计会失去多模态功能

谢谢大佬😁

**Comment by woodchen-ink** [comment]
``` shell
curl https://api.anthropic.com/v1/messages --header "x-api-key: YOUR_API_KEY" ...
```

就还是多个`/v1`的事, 也不知道cf为啥这么设置

**Comment by MartialBE** [comment]
填写 https://gateway.ai.cloudflare.com/v1/feedd0aaxxxxxxxxxxxx/xxxx/anthropic 即可。

**Comment by woodchen-ink** [comment]
> 填写 https://gateway.ai.cloudflare.com/v1/feedd0aaxxxxxxxxxxxx/xxxx/anthropic 即可。

多谢大哥

**Comment by MartialBE** [comment]
不过不建议 使用 cloudflare gateway。
因为 anthropic 同样使用 cloudflare 的服务。
cloudflare 会将你真实IP传递给 anthropic，如果为了风控 使用cloudflare 没有意义的。
这是我在cloudflare搭建的服务，我可以查看到访问者的真实IP

<img width="1004" alt="iShot_2024-03-11_11 59 25" src="https://github.com/MartialBE/one-api/assets/42402987/72c9bcc0-4ef3-453c-9638-99a4f811b502">

**Comment by woodchen-ink** [comment]
> 不过不建议 使用 cloudflare gateway。 因为 anthropic 同样使用 cloudflare 的服务。 cloudflare 会将你真实IP传递给 anthropic，如果为了风控 使用cloudflare 没有意义的。 这是我在cloudflare搭建的服务，我可以查看到访问者的真实IP
> 
> <img alt="iShot_2024-03-11_11 59 25" width="1004" src="https://private-user-images.githubusercontent.com/42402987/311582261-72c9bcc0-4ef3-453c-9638-99a4f811b502.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMzA3MTIsIm5iZiI6MTcxMDEzMDQxMiwicGF0aCI6Ii80MjQwMjk4Ny8zMTE1ODIyNjEtNzJjOWJjYzAtNGVmMy00NTNjLTk2MzgtOTlhNGY4MTFiNTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA0MTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5OWM2ZDc0ZWNhMGM0MWZkNWRkZjk2NTI0MWM1ZjU0ZmY3NTQ1ZmQ5MDhmYWU3OTc1ZTEyOTY0NzkzOGZhMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.20l5DOeoer1dVv7JjDfhBXr8OZ4eS6JPlIGdRvJwmrM">

是的……用了 cf gateway 也无法访问
![image](https://github.com/MartialBE/one-api/assets/95951386/f6261c44-48dd-4c41-ad04-a8403262bd16)

**Comment by woodchen-ink** [comment]
不仅这个不行,连cf worker反代,vercel反代都不可以, anthropic这个还挺严的

**Comment by MartialBE** [comment]
我已经懒得玩它了... 
我两个号都被封了... 我openai都没这么折腾。心累。

**Comment by woodchen-ink** [comment]
> 我已经懒得玩它了... 我两个号都被封了... 我openai都没这么折腾。心累。

haha, 我通过 vpn 调用的目前还没封，还是新加坡的机子好

**Comment by woodchen-ink** [comment]
![image](https://github.com/MartialBE/one-api/assets/95951386/4475b5ee-1c24-44f8-aab3-796f4e1feba5)
太严格了
