### ISSUE TITLE
咨询下 azure 的问题

### ISSUE THREAD

**Issue by woodchen-ink** [MartialBE/one-api#99]
azure 的渠道目前调用的时候，之前有个逻辑，是把后四位数字删掉，但我现在用好像没删，是取消这个函数了吗？

我 openai 的账号被改预付费了😭

![image](https://github.com/MartialBE/one-api/assets/95951386/8ffa5fc8-f5d2-4620-bbb4-25144302544b)
比如我部署的这个，怎么让 `gpt-3.5-turbo-0613`指向这个`gpt-3.5-turbo`呢，作者现在是怎么用的？

还是我自己设置模型重定向比较好？

**Comment by MartialBE** [comment]
直接设定映射 
这个逻辑去掉了。只会处理模型名称中的 . 
因为去掉后四位有点问题，不同的3.5 max token会不同。 azure也可以创建不同版本的3.5。

**Comment by woodchen-ink** [comment]
> 直接设定映射 这个逻辑去掉了。只会处理模型名称中的 . 因为去掉后四位有点问题，不同的3.5 max token会不同。 azure也可以创建不同版本的3.5。

好的👌
